//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEC_SOLICITUD_BECA
    {
        public long idSolicitud { get; set; }
        public long idPersona { get; set; }
        public System.DateTime fecha { get; set; }
        public bool pregunta_1 { get; set; }
        public bool pregunta_2 { get; set; }
        public bool pregunta_3 { get; set; }
        public bool pregunta_4 { get; set; }
        public bool pregunta_5 { get; set; }
        public bool pregunta_6 { get; set; }
        public bool pregunta_7 { get; set; }
        public bool pregunta_8 { get; set; }
        public bool pregunta_9 { get; set; }
        public string pregunta_10 { get; set; }
        public string documentos { get; set; }
        public string datos_anteriores { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
