//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG_USU
    {
        public int BU_CATID { get; set; }
        public int BU_USUID { get; set; }
    
        public virtual CATEGORIA_CAT CATEGORIA_CAT { get; set; }
    }
}
