//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG_USU
    {
        public int BU_CATID { get; set; }
        public int BU_USUID { get; set; }
    
        public virtual CATEGORIA_CAT CATEGORIA_CAT { get; set; }
    }
}
