//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EXPERTOS
    {
        public long Id_Experto { get; set; }
        public string Nombre { get; set; }
        public string Foto { get; set; }
        public string Comentario { get; set; }
        public string Url_Twitter { get; set; }
        public string Url_Linkedin { get; set; }
        public Nullable<decimal> Id_Curso { get; set; }
        public decimal Principal { get; set; }
        public decimal Consejo { get; set; }
    }
}
