//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EXPERTOS
    {
        public long Id_Experto { get; set; }
        public string Nombre { get; set; }
        public string Foto { get; set; }
        public string Comentario { get; set; }
        public string Url_Twitter { get; set; }
        public string Url_Linkedin { get; set; }
        public Nullable<decimal> Id_Curso { get; set; }
        public decimal Principal { get; set; }
        public decimal Consejo { get; set; }
    }
}
