//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_RD_DOC_CUR
    {
        public long id_RecursoDirecto { get; set; }
        public long ID_Docencia { get; set; }
        public long ID_Curso { get; set; }
        public Nullable<int> orden { get; set; }
    
        public virtual campus_CURSO campus_CURSO { get; set; }
        public virtual campus_RD_Doc campus_RD_Doc { get; set; }
    }
}
