//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_WORKFLOW_PREGUNTAS
    {
        public long id_WF_Pregunta { get; set; }
        public long id_WF_Docencia { get; set; }
        public Nullable<long> id_WF_Grupo { get; set; }
        public Nullable<long> id_WF_Paso { get; set; }
        public long id_User { get; set; }
        public string pregunta { get; set; }
        public System.DateTime fecha_pregunta { get; set; }
        public string respuesta { get; set; }
        public Nullable<System.DateTime> fecha_respuesta { get; set; }
        public Nullable<long> id_WF_Pregunta_Padre { get; set; }
        public Nullable<System.DateTime> fecha_view { get; set; }
        public bool privada { get; set; }
    }
}
