//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_OTROS
    {
        public long ID_Otros { get; set; }
        public long id_cliente { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> Tipo { get; set; }
        public string URL { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
