//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DOCENCIA_EXAMEN
    {
        public long ID_Docencia_Examen { get; set; }
        public long ID_Docencia { get; set; }
        public long ID_Persona { get; set; }
        public long ID_Curso_Examen { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora_Inicio { get; set; }
        public Nullable<System.DateTime> Hora_Fin { get; set; }
        public string Comentarios { get; set; }
        public decimal Apto { get; set; }
        public decimal Puntuacion { get; set; }
    }
}
