//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_WORKFLOW_PREGUNTAS
    {
        public long id_WF_Pregunta { get; set; }
        public long id_WF_Docencia { get; set; }
        public Nullable<long> id_WF_Grupo { get; set; }
        public Nullable<long> id_WF_Paso { get; set; }
        public long id_User { get; set; }
        public string pregunta { get; set; }
        public System.DateTime fecha_pregunta { get; set; }
        public string respuesta { get; set; }
        public Nullable<System.DateTime> fecha_respuesta { get; set; }
        public Nullable<long> id_WF_Pregunta_Padre { get; set; }
        public Nullable<System.DateTime> fecha_view { get; set; }
        public bool privada { get; set; }
    }
}
