//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_FORO_RESPUESTA
    {
        public long ID_MsgR_Foro { get; set; }
        public string Titulo { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public long ID_Persona { get; set; }
        public long ID_Msg_Foro { get; set; }
        public long ID_Foro { get; set; }
        public string Borrador { get; set; }
        public Nullable<long> Resp_id_persona { get; set; }
        public Nullable<System.DateTime> Resp_fecha { get; set; }
    }
}
