//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_REC_CP_TRABAJO
    {
        public long idCPTrabajo { get; set; }
        public long idCP { get; set; }
        public long id_alumno { get; set; }
        public bool leido_enunciado { get; set; }
        public Nullable<System.DateTime> cp_fecha { get; set; }
        public string cp_fichero { get; set; }
        public string cp_comentarios { get; set; }
        public bool leido_feedback { get; set; }
        public Nullable<System.DateTime> feedback_fecha { get; set; }
        public string feedback_fichero { get; set; }
        public string feedback_comentarios { get; set; }
        public bool bloqueado { get; set; }
    
        public virtual campus_REC_CP campus_REC_CP { get; set; }
    }
}
