//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_EDUCACION
    {
        public long ID_Educacion { get; set; }
        public long id_cliente { get; set; }
        public string Tipo_Programa { get; set; }
        public string Programa { get; set; }
        public Nullable<System.DateTime> Fecha_Convocatoria { get; set; }
        public Nullable<long> Nivel_Educativo { get; set; }
        public string Campo_Estudio { get; set; }
        public string Titulacion { get; set; }
        public string Centro { get; set; }
        public Nullable<long> Pais { get; set; }
        public string Poblacion { get; set; }
        public Nullable<long> Idioma { get; set; }
        public Nullable<System.DateTime> FInicio { get; set; }
        public Nullable<System.DateTime> FFin { get; set; }
        public string Observaciones { get; set; }
        public Nullable<long> Lang { get; set; }
        public Nullable<long> Nivel { get; set; }
        public string Observaciones_Lang { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
