//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_AUTO_DOCENCIA
    {
        public long ID_Docencia { get; set; }
        public long ID_Curso { get; set; }
        public long Id_Automatizacion { get; set; }
    }
}
