//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CONTENIDO_EXAMEN
    {
        public long ID_Contenido_Examen { get; set; }
        public long ID_Curso_Examen { get; set; }
        public string Pregunta { get; set; }
        public string Respuesta1 { get; set; }
        public string Respuesta2 { get; set; }
        public string Respuesta3 { get; set; }
        public string Respuesta4 { get; set; }
        public string Respuesta5 { get; set; }
        public string Respuesta6 { get; set; }
        public string Respuesta7 { get; set; }
        public Nullable<int> Solucion { get; set; }
        public int Tipo_Pregunta { get; set; }
        public string Respuesta_Abierta { get; set; }
        public int Orden { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Procesado { get; set; }
    }
}
