//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_ED_ANTERIOR
    {
        public long id_edicion_anterior { get; set; }
        public long idCurso { get; set; }
        public string tipo_recurso { get; set; }
        public string recurso_fichero { get; set; }
        public string recurso_texto { get; set; }
        public string recurso_add { get; set; }
    }
}
