//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_AGENDA
    {
        public long ID_Agenda { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Titulo { get; set; }
        public Nullable<long> ID_Docencia_Grupo { get; set; }
        public Nullable<long> ID_Docencia_Subgrupo { get; set; }
        public long ID_Persona_Publica { get; set; }
        public System.DateTime Fecha_Publica { get; set; }
        public Nullable<long> idCurso { get; set; }
        public Nullable<int> idTipo { get; set; }
        public Nullable<System.DateTime> Hora_Inicio { get; set; }
        public Nullable<System.DateTime> Hora_Fin { get; set; }
        public Nullable<bool> All_Day { get; set; }
        public Nullable<bool> Pendiente { get; set; }
    }
}
