//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CURSO_EXAMEN
    {
        public long ID_Curso_Examen { get; set; }
        public string Titulo { get; set; }
        public string Normas { get; set; }
        public string Comentarios { get; set; }
        public long ID_Curso { get; set; }
        public Nullable<int> Num_Preguntas { get; set; }
        public Nullable<int> Num_Respuestas { get; set; }
        public Nullable<int> Apto { get; set; }
        public int Minutos { get; set; }
        public Nullable<bool> AutoCorregir { get; set; }
        public Nullable<int> Num_Realizados { get; set; }
        public Nullable<int> Num_Aptos { get; set; }
        public Nullable<decimal> Nota_Media { get; set; }
    }
}
