//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_ACCIONES_PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campus_ACCIONES_PERSONA()
        {
            this.campus_SEG_COMERCIAL = new HashSet<campus_SEG_COMERCIAL>();
        }
    
        public long idAccionPersona { get; set; }
        public long idPersona { get; set; }
        public long idAccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<long> IdOrigen { get; set; }
        public Nullable<decimal> IdCurso { get; set; }
        public string Comentario { get; set; }
        public string Cookie { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public string Http_Accept { get; set; }
        public string Http_Accept_Encoding { get; set; }
        public string Http_Accept_Language { get; set; }
        public string Http_Connection { get; set; }
        public string Http_Cookie { get; set; }
        public string Http_Host { get; set; }
        public string Http_Referer { get; set; }
        public string Http_User_Agent { get; set; }
        public string Http_IP { get; set; }
        public string Http_URL { get; set; }
        public Nullable<int> Scoring { get; set; }
        public Nullable<bool> test_interno { get; set; }
        public Nullable<long> idLanding { get; set; }
        public Nullable<System.DateTime> Fecha_prox_envio { get; set; }
        public Nullable<int> Accion_Nurturing { get; set; }
        public string Http_Country { get; set; }
        public string Http_IP_info { get; set; }
        public string Http_Variables { get; set; }
        public string Http_source { get; set; }
        public string Http_source_details { get; set; }
        public Nullable<int> idPais { get; set; }
        public string utm_source { get; set; }
        public string utm_medium { get; set; }
        public string utm_campaign { get; set; }
        public string utm_term { get; set; }
        public string utm_content { get; set; }
        public Nullable<bool> tag_process { get; set; }
        public string tags { get; set; }
        public Nullable<long> idComercial { get; set; }
        public Nullable<int> estado_lead { get; set; }
        public string ult_comentario { get; set; }
        public Nullable<int> scoring_lead { get; set; }
        public string resumen_metodologia { get; set; }
        public string resumen_cuando { get; set; }
        public string resumen_comentarios { get; set; }
        public Nullable<int> resumen_beca { get; set; }
        public Nullable<int> resumen_descuento { get; set; }
        public Nullable<System.DateTime> resumen_fecha_act { get; set; }
        public Nullable<System.DateTime> ult_seg_fecha { get; set; }
        public Nullable<long> idPertenencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_SEG_COMERCIAL> campus_SEG_COMERCIAL { get; set; }
    }
}
