//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_RD_Asistencia
    {
        public long id_RecursoDirecto { get; set; }
        public long ID_Persona { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Procesado { get; set; }
        public Nullable<int> Modalidad { get; set; }
    
        public virtual campus_RECURSO_DIRECTO campus_RECURSO_DIRECTO { get; set; }
    }
}
