//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CLIENTES_DOC
    {
        public long idClienteDoc { get; set; }
        public long idCliente { get; set; }
        public string tipo_documento { get; set; }
        public string Descripcion { get; set; }
        public string Fichero { get; set; }
        public Nullable<System.DateTime> fecha_caducidad { get; set; }
        public Nullable<long> id_docencia { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
