//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_LITERALES
    {
        public long ID_Literales { get; set; }
        public long ID_Padre { get; set; }
        public long Valor1 { get; set; }
        public string Descripcion { get; set; }
    }
}
