//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_RECURSO_STATUS
    {
        public long ID_Recurso { get; set; }
        public long ID_Persona { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Tiempo { get; set; }
        public bool Terminado { get; set; }
    
        public virtual campus_RECURSO campus_RECURSO { get; set; }
    }
}
