//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DOCENCIA_TUTORIAS
    {
        public long id_tutoria { get; set; }
        public long id_docencia { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public Nullable<long> id_alumno { get; set; }
        public Nullable<long> id_curso { get; set; }
        public string tipo { get; set; }
        public string comentario_solicitud { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fecha_planificacion { get; set; }
        public Nullable<long> id_tutor { get; set; }
        public string comentario_planificacion { get; set; }
        public Nullable<System.DateTime> fecha_realizacion { get; set; }
        public string comentario_realizacion { get; set; }
        public string evidencia_realizacion { get; set; }
    }
}
