//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CLIENTES_COMERCIAL
    {
        public long idCliente { get; set; }
        public long idPertenencia { get; set; }
        public string MailPertenencia { get; set; }
    
        public virtual campus_AUX campus_AUX { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
