//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_ENCUESTA
    {
        public long ID_Encuesta { get; set; }
        public long ID_Persona { get; set; }
        public long ID_Docencia { get; set; }
        public long ID_Curso { get; set; }
        public System.DateTime Fecha { get; set; }
        public int P11 { get; set; }
        public int P12 { get; set; }
        public int P13 { get; set; }
        public int P14 { get; set; }
        public int P15 { get; set; }
        public int P16 { get; set; }
        public int P17 { get; set; }
        public int P21 { get; set; }
        public int P22 { get; set; }
        public int P23 { get; set; }
        public int P24 { get; set; }
        public int P31 { get; set; }
        public int P32 { get; set; }
        public int P33 { get; set; }
        public int P34 { get; set; }
        public int P35 { get; set; }
        public int P41 { get; set; }
        public int P42 { get; set; }
        public int P43 { get; set; }
        public string P5_Sugerencias { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
