//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_REC_CP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campus_REC_CP()
        {
            this.campus_REC_CP_TRABAJO = new HashSet<campus_REC_CP_TRABAJO>();
        }
    
        public long idCP { get; set; }
        public long id_Docencia { get; set; }
        public long id_Curso { get; set; }
        public long id_Profesor { get; set; }
        public System.DateTime cp_fecha { get; set; }
        public string cp_fichero { get; set; }
        public string cp_comentarios { get; set; }
        public System.DateTime cp_fecha_max { get; set; }
        public Nullable<bool> pendiente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_REC_CP_TRABAJO> campus_REC_CP_TRABAJO { get; set; }
    }
}
