//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DOCENCIA_GRUPO
    {
        public long idDocenciaGrupo { get; set; }
        public long ID_Docencia { get; set; }
        public long ID_Persona { get; set; }
        public Nullable<decimal> PrecioPagado { get; set; }
        public string Comentarios { get; set; }
        public string Comentario_Alumno { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaDesistimiento { get; set; }
        public Nullable<System.DateTime> FFinAcceso { get; set; }
        public Nullable<bool> Procesado { get; set; }
    }
}
