//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_REGLAS_ACCIONES
    {
        public long idReglaAccion { get; set; }
        public long idRegla { get; set; }
        public long idTipo { get; set; }
        public string tags { get; set; }
        public Nullable<int> canal { get; set; }
        public Nullable<int> estado { get; set; }
        public string comentario { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<long> idComercial { get; set; }
        public string nombreFrom { get; set; }
        public string mailFrom { get; set; }
        public string replyTo { get; set; }
        public string asunto { get; set; }
        public string body { get; set; }
        public string adjuntos { get; set; }
        public string cco { get; set; }
    }
}
