//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CONTENIDO_DOCENCIA
    {
        public long ID_Contenido_Docencia { get; set; }
        public long ID_Docencia { get; set; }
        public long ID_Curso { get; set; }
        public long ID_Recurso { get; set; }
        public string COD_Curso { get; set; }
        public string COD_Recurso { get; set; }
        public decimal Sesion { get; set; }
        public Nullable<decimal> Lectura { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Visible { get; set; }
        public Nullable<System.DateTime> Fecha_Limite_Ord { get; set; }
        public string Comentarios_Ord { get; set; }
        public Nullable<System.DateTime> Fecha_Limite_Ext { get; set; }
        public string Comentarios_Ext { get; set; }
        public Nullable<System.DateTime> Fecha_Limite_Gra { get; set; }
        public string Comentarios_Gra { get; set; }
    }
}
