//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_RD_Doc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campus_RD_Doc()
        {
            this.campus_RD_DOC_CUR = new HashSet<campus_RD_DOC_CUR>();
        }
    
        public long id_RecursoDirecto { get; set; }
        public long ID_Docencia { get; set; }
        public Nullable<int> orden { get; set; }
    
        public virtual campus_DOCENCIA campus_DOCENCIA { get; set; }
        public virtual campus_RECURSO_DIRECTO campus_RECURSO_DIRECTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_RD_DOC_CUR> campus_RD_DOC_CUR { get; set; }
    }
}
