//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_FORO_ADJUNTOS
    {
        public long ID_Adjunto { get; set; }
        public decimal Depende_De { get; set; }
        public long ID_Mensaje { get; set; }
        public long ID_Foro { get; set; }
        public string Titulo { get; set; }
        public string Adjunto_Fichero { get; set; }
        public string Adjunto_Url { get; set; }
    }
}
