//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CONTENIDO_CURSO
    {
        public long ID_Contenido_Curso { get; set; }
        public long ID_Curso { get; set; }
        public long ID_Recurso { get; set; }
        public string COD_Curso { get; set; }
        public string COD_Recurso { get; set; }
        public int Sesion { get; set; }
        public int Lectura { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
