//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DATA_COMERCIAL
    {
        public long idDataComercial { get; set; }
        public long idAlumno { get; set; }
        public long idCurso { get; set; }
        public long idDocencia { get; set; }
        public System.DateTime Fecha_est { get; set; }
        public decimal EUR_est { get; set; }
        public Nullable<System.DateTime> Fecha_real { get; set; }
        public Nullable<decimal> EUR_real { get; set; }
    }
}
