//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DOCENCIA_GRUPO_REC_PRACT
    {
        public long idAlumno { get; set; }
        public long idDocencia { get; set; }
        public long idCurso { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Tipo { get; set; }
        public string Huella { get; set; }
        public string Adj1_file { get; set; }
        public string Adj1_descripcion { get; set; }
        public string Adj2_file { get; set; }
        public string Adj2_descripcion { get; set; }
        public string Adj3_file { get; set; }
        public string Adj3_descripcion { get; set; }
        public string Adj4_file { get; set; }
        public string Adj4_descripcion { get; set; }
        public string Adj5_file { get; set; }
        public string Adj5_descripcion { get; set; }
    
        public virtual campus_CURSO campus_CURSO { get; set; }
        public virtual campus_DOCENCIA campus_DOCENCIA { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
