//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_WORKFLOW_AVANCE
    {
        public long id_WF_Avance { get; set; }
        public long id_WF_Paso { get; set; }
        public long id_user { get; set; }
        public Nullable<System.DateTime> fecha_view { get; set; }
    
        public virtual campus_WORKFLOW_PASO campus_WORKFLOW_PASO { get; set; }
    }
}
