//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_WORKFLOW_AVANCE
    {
        public long id_WF_Avance { get; set; }
        public long id_WF_Paso { get; set; }
        public long id_user { get; set; }
        public Nullable<System.DateTime> fecha_view { get; set; }
    
        public virtual campus_WORKFLOW_PASO campus_WORKFLOW_PASO { get; set; }
    }
}
