//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DOCENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campus_DOCENCIA()
        {
            this.campus_RD_Doc = new HashSet<campus_RD_Doc>();
            this.CampusCursoOnline = new HashSet<CampusCursoOnline>();
            this.campus_DOCENCIA_GRUPO_REC_PRACT = new HashSet<campus_DOCENCIA_GRUPO_REC_PRACT>();
        }
    
        public long ID_Docencia { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> FInicio { get; set; }
        public Nullable<System.DateTime> FFin { get; set; }
        public long ID_Curso { get; set; }
        public Nullable<bool> Renuncia_Desistimiento { get; set; }
        public Nullable<bool> PDP { get; set; }
        public Nullable<bool> WorkFlow { get; set; }
        public string Curso { get; set; }
        public Nullable<long> idAsociado { get; set; }
        public Nullable<bool> Encuesta_Especial { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<System.DateTime> FFinAcceso { get; set; }
        public string File_Calendario { get; set; }
        public string File_Acta { get; set; }
        public string File_Indicadores { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_RD_Doc> campus_RD_Doc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampusCursoOnline> CampusCursoOnline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_DOCENCIA_GRUPO_REC_PRACT> campus_DOCENCIA_GRUPO_REC_PRACT { get; set; }
    }
}
