//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_EXPERIENCIA_PROFESIONAL
    {
        public long ID_Exp { get; set; }
        public long id_cliente { get; set; }
        public string Empresa { get; set; }
        public Nullable<long> ParaQuien { get; set; }
        public Nullable<long> Cargo { get; set; }
        public string Nombre_Cargo { get; set; }
        public Nullable<System.DateTime> FInicio { get; set; }
        public Nullable<System.DateTime> FFin { get; set; }
        public Nullable<long> Area { get; set; }
        public string Sector { get; set; }
        public Nullable<long> Pais { get; set; }
        public Nullable<long> Provincia { get; set; }
        public string Poblacion { get; set; }
        public string Funciones { get; set; }
        public string Telefono_Empresa { get; set; }
        public Nullable<int> Antiguedad { get; set; }
        public string Rango_Salarial { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
