//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DOCENCIA_GRUPO_EVALUACION
    {
        public long idEvaluacion { get; set; }
        public long idPersona { get; set; }
        public long idCurso { get; set; }
        public long idDocencia { get; set; }
        public System.DateTime fecha { get; set; }
        public string calificacion { get; set; }
        public Nullable<decimal> nota { get; set; }
        public string comentarios { get; set; }
        public Nullable<long> idProfesor { get; set; }
        public Nullable<System.DateTime> ord_fecha { get; set; }
        public string ord_calificacion { get; set; }
        public Nullable<decimal> ord_nota { get; set; }
        public string ord_comentarios { get; set; }
        public Nullable<long> ord_idProfesor { get; set; }
        public Nullable<System.DateTime> ext_fecha { get; set; }
        public string ext_calificacion { get; set; }
        public Nullable<decimal> ext_nota { get; set; }
        public string ext_comentarios { get; set; }
        public Nullable<long> ext_idProfesor { get; set; }
        public Nullable<System.DateTime> gra_fecha_act { get; set; }
        public Nullable<System.DateTime> gra_fecha_limite { get; set; }
        public string gra_calificacion { get; set; }
        public Nullable<decimal> gra_nota { get; set; }
        public string gra_comentarios { get; set; }
        public Nullable<long> gra_idProfesor { get; set; }
        public string comentarios_finales { get; set; }
    }
}
