//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_OPINIONES
    {
        public long IdOpinion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Nombre { get; set; }
        public string Cargo { get; set; }
        public string Curso { get; set; }
        public string Comentario { get; set; }
        public string Foto { get; set; }
        public string Video { get; set; }
        public Nullable<long> IdPersona { get; set; }
        public Nullable<long> IdCurso { get; set; }
        public Nullable<long> IdDocencia { get; set; }
        public Nullable<long> id_os { get; set; }
        public Nullable<bool> permite_contacto { get; set; }
        public Nullable<int> valoracion { get; set; }
        public string huella { get; set; }
        public Nullable<bool> recomendacion { get; set; }
        public Nullable<bool> visible { get; set; }
        public string texto_pregunta { get; set; }
    }
}
