//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_PLANTILLA_MAIL
    {
        public long idPlantillaMail { get; set; }
        public long idCurso { get; set; }
        public long idQuien { get; set; }
        public string nombre_plantilla { get; set; }
        public string asunto { get; set; }
        public string cuerpo { get; set; }
        public string adjunto_1 { get; set; }
        public string adjunto_2 { get; set; }
        public string adjunto_3 { get; set; }
        public string adjunto_4 { get; set; }
        public string adjunto_5 { get; set; }
    }
}
