//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_OPINIONES_SOLICITUD
    {
        public long id_solicitud_opinion { get; set; }
        public long id_docencia { get; set; }
        public int id_tso { get; set; }
        public System.DateTime fecha { get; set; }
        public string nombreFrom { get; set; }
        public string mailFrom { get; set; }
        public string replyTo { get; set; }
        public string asunto { get; set; }
        public string body { get; set; }
        public bool procesado { get; set; }
    }
}
