//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_PDP
    {
        public long idPDP { get; set; }
        public System.DateTime fecha { get; set; }
        public long idCliente { get; set; }
        public int num_Cursos { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string mail_supervisor { get; set; }
        public string comentarios { get; set; }
        public string titulo_PDP { get; set; }
        public Nullable<long> idDocencia_1 { get; set; }
        public Nullable<long> idDocencia_2 { get; set; }
        public Nullable<long> idDocencia_3 { get; set; }
        public Nullable<long> idDocencia_4 { get; set; }
        public Nullable<long> idDocencia_5 { get; set; }
        public Nullable<long> idDocencia_6 { get; set; }
        public Nullable<long> idDocencia_7 { get; set; }
        public Nullable<long> idDocencia_8 { get; set; }
        public Nullable<long> idDocencia_9 { get; set; }
        public Nullable<long> idDocencia_10 { get; set; }
        public Nullable<bool> procesado { get; set; }
        public Nullable<bool> tag_process { get; set; }
    }
}
