//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CLASE_ASISTENCIA
    {
        public long idcs { get; set; }
        public System.DateTime fecha { get; set; }
        public long idAlumno { get; set; }
        public string titulo_clase { get; set; }
        public long idDocenciaGlobal { get; set; }
        public long idDocencia { get; set; }
        public int tipo_clase { get; set; }
        public Nullable<System.DateTime> pregunta_fecha { get; set; }
        public Nullable<int> pregunta_respuesta { get; set; }
        public string pregunta_historico { get; set; }
        public string pregunta_motivo { get; set; }
        public Nullable<System.DateTime> respuesta_fecha { get; set; }
        public string respuesta_ip { get; set; }
        public string respuesta_info { get; set; }
        public Nullable<long> respuesta_idEncuesta { get; set; }
        public Nullable<int> respuesta_respuesta { get; set; }
        public string respuesta_motivo { get; set; }
    }
}
