//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_AUTO_CURSO
    {
        public long Id_Automatizacion { get; set; }
        public long ID_Curso { get; set; }
        public int Tipo { get; set; }
        public string Asunto { get; set; }
        public string Descripcion { get; set; }
        public string Adjuntos { get; set; }
        public Nullable<long> Id_Foro { get; set; }
        public Nullable<int> Num_Dias_Fecha_Limite { get; set; }
        public Nullable<long> Id_Recurso { get; set; }
        public int Num_Dias { get; set; }
    }
}
