//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_ACTIVACIONES_PDP
    {
        public long idActivacion_PDP { get; set; }
        public string key_Activacion { get; set; }
        public long idCliente { get; set; }
        public long idPDP { get; set; }
        public bool activado { get; set; }
    }
}
