//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DOCENCIA_EXAMEN
    {
        public long ID_Docencia_Examen { get; set; }
        public long ID_Docencia { get; set; }
        public long ID_Persona { get; set; }
        public long ID_Curso_Examen { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora_Inicio { get; set; }
        public Nullable<System.DateTime> Hora_Fin { get; set; }
        public string Comentarios { get; set; }
        public decimal Apto { get; set; }
        public decimal Puntuacion { get; set; }
    }
}
