//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_WORKFLOW_GRUPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campus_WORKFLOW_GRUPO()
        {
            this.campus_WORKFLOW_PASO = new HashSet<campus_WORKFLOW_PASO>();
        }
    
        public long id_WF_Grupo { get; set; }
        public long id_WF_Docencia { get; set; }
        public string nombre { get; set; }
        public Nullable<long> id_Curso { get; set; }
        public int orden { get; set; }
    
        public virtual campus_WORKFLOW_DOCENCIA campus_WORKFLOW_DOCENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_WORKFLOW_PASO> campus_WORKFLOW_PASO { get; set; }
    }
}
