//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_WORKFLOW_PASO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campus_WORKFLOW_PASO()
        {
            this.campus_WORKFLOW_AVANCE = new HashSet<campus_WORKFLOW_AVANCE>();
        }
    
        public long id_WF_Paso { get; set; }
        public long id_WF_Grupo { get; set; }
        public long id_Recurso { get; set; }
        public string nombre { get; set; }
        public int orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_WORKFLOW_AVANCE> campus_WORKFLOW_AVANCE { get; set; }
        public virtual campus_WORKFLOW_GRUPO campus_WORKFLOW_GRUPO { get; set; }
    }
}
