//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_RECURSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campus_RECURSO()
        {
            this.campus_RD_R = new HashSet<campus_RD_R>();
            this.campus_RECURSO_STATUS = new HashSet<campus_RECURSO_STATUS>();
        }
    
        public long ID_Recurso { get; set; }
        public string COD_Recurso { get; set; }
        public string Descripcion { get; set; }
        public int ID_Tipo_Recurso { get; set; }
        public int ID_Area_Funcional { get; set; }
        public string Titulo { get; set; }
        public string Activo { get; set; }
        public int Version { get; set; }
        public string Derechos { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<System.DateTime> FBaja { get; set; }
        public string Rec_Interno { get; set; }
        public string Rec_Externo { get; set; }
        public Nullable<int> Duracion { get; set; }
        public string Key { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_RD_R> campus_RD_R { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_RECURSO_STATUS> campus_RECURSO_STATUS { get; set; }
    }
}
