//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_OTROS
    {
        public long ID_Otros { get; set; }
        public long id_cliente { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> Tipo { get; set; }
        public string URL { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
