//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DATA_COMERCIAL
    {
        public long idDataComercial { get; set; }
        public long idAlumno { get; set; }
        public long idCurso { get; set; }
        public long idDocencia { get; set; }
        public System.DateTime Fecha_est { get; set; }
        public decimal EUR_est { get; set; }
        public Nullable<System.DateTime> Fecha_real { get; set; }
        public Nullable<decimal> EUR_real { get; set; }
    }
}
