//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_SEG_COMERCIAL
    {
        public long id_SegComercial { get; set; }
        public System.DateTime fecha { get; set; }
        public long idCurso { get; set; }
        public long idComercial { get; set; }
        public long idAlumno { get; set; }
        public string Comentarios { get; set; }
        public Nullable<bool> Cerrado { get; set; }
        public Nullable<bool> Rechazado { get; set; }
        public Nullable<bool> Duplicado { get; set; }
        public Nullable<bool> Futuro { get; set; }
        public Nullable<bool> Matriculado { get; set; }
        public long idAccionPersona { get; set; }
        public string tipo { get; set; }
        public Nullable<int> accion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> fundacion { get; set; }
        public Nullable<int> descuento { get; set; }
        public Nullable<long> idPlantillaMail { get; set; }
        public Nullable<long> idMail { get; set; }
        public Nullable<bool> recordatorio { get; set; }
        public Nullable<bool> leer { get; set; }
        public string Asunto_mail { get; set; }
        public string Cuerpo_mail { get; set; }
        public string Adjuntos_mail { get; set; }
    
        public virtual campus_ACCIONES_PERSONA campus_ACCIONES_PERSONA { get; set; }
    }
}
