//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DOCENCIA_SUBGRUPO
    {
        public long ID_Docencia_Subgrupo { get; set; }
        public long ID_Docencia { get; set; }
        public long ID_Persona { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    }
}
