//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_ANUNCIO
    {
        public long ID_Anuncio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Titulo { get; set; }
        public string Cuerpo { get; set; }
        public Nullable<long> ID_Docencia_Grupo { get; set; }
        public Nullable<long> ID_Docencia_Subgrupo { get; set; }
        public Nullable<long> ID_Persona { get; set; }
        public long Tipo_Anuncio { get; set; }
        public Nullable<long> ID_Curso { get; set; }
        public long ID_Persona_Publica { get; set; }
        public System.DateTime Fecha_Publica { get; set; }
        public Nullable<long> Id_Mail { get; set; }
        public Nullable<long> Resp_id_persona { get; set; }
        public Nullable<System.DateTime> Resp_fecha { get; set; }
        public Nullable<bool> Leido { get; set; }
        public string Adjuntos { get; set; }
        public Nullable<bool> Pendiente { get; set; }
    }
}
