//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DOCENCIA_GRUPO
    {
        public long idDocenciaGrupo { get; set; }
        public long ID_Docencia { get; set; }
        public long ID_Persona { get; set; }
        public Nullable<decimal> PrecioPagado { get; set; }
        public string Comentarios { get; set; }
        public string Comentario_Alumno { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaDesistimiento { get; set; }
        public Nullable<System.DateTime> FFinAcceso { get; set; }
        public Nullable<bool> Procesado { get; set; }
    }
}
