//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CURSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campus_CURSO()
        {
            this.campus_RD_DOC_CUR = new HashSet<campus_RD_DOC_CUR>();
            this.CampusCursoOnline = new HashSet<CampusCursoOnline>();
            this.CampusCursoOnlineAfiliado = new HashSet<CampusCursoOnlineAfiliado>();
            this.campus_DOCENCIA_GRUPO_REC_PRACT = new HashSet<campus_DOCENCIA_GRUPO_REC_PRACT>();
        }
    
        public long ID_Curso { get; set; }
        public string COD_Curso { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> FAlta { get; set; }
        public Nullable<System.DateTime> FBaja { get; set; }
        public bool Activo { get; set; }
        public int Version { get; set; }
        public string ProgramaPDF { get; set; }
        public Nullable<int> Num_Sesiones { get; set; }
        public Nullable<int> ID_Area_Funcional { get; set; }
        public Nullable<int> Num_Cursos { get; set; }
        public Nullable<decimal> Tipo_Curso { get; set; }
        public Nullable<int> ID_Responsable { get; set; }
        public Nullable<decimal> Gratuito { get; set; }
        public Nullable<int> numHoras { get; set; }
        public string TIT_Oficial { get; set; }
        public string CONT_Oficial { get; set; }
        public string ProgramaPDFCompleto { get; set; }
        public string ProgramaPDFWeb { get; set; }
        public Nullable<int> idMetodologia { get; set; }
        public Nullable<int> idTipo_Curso { get; set; }
        public Nullable<int> idDificultad { get; set; }
        public Nullable<bool> universitario { get; set; }
        public Nullable<int> duracion { get; set; }
        public string calendario { get; set; }
        public string sistema_evaluacion { get; set; }
        public Nullable<decimal> ECTS { get; set; }
        public Nullable<bool> Web { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> generar_titulo { get; set; }
        public Nullable<int> plan_num_dias { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_RD_DOC_CUR> campus_RD_DOC_CUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampusCursoOnline> CampusCursoOnline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampusCursoOnlineAfiliado> CampusCursoOnlineAfiliado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_DOCENCIA_GRUPO_REC_PRACT> campus_DOCENCIA_GRUPO_REC_PRACT { get; set; }
    }
}
