//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DOCENCIA_GRUPO_REC_PRACT
    {
        public long idAlumno { get; set; }
        public long idDocencia { get; set; }
        public long idCurso { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Tipo { get; set; }
        public string Huella { get; set; }
        public string Adj1_file { get; set; }
        public string Adj1_descripcion { get; set; }
        public string Adj2_file { get; set; }
        public string Adj2_descripcion { get; set; }
        public string Adj3_file { get; set; }
        public string Adj3_descripcion { get; set; }
        public string Adj4_file { get; set; }
        public string Adj4_descripcion { get; set; }
        public string Adj5_file { get; set; }
        public string Adj5_descripcion { get; set; }
    
        public virtual campus_CURSO campus_CURSO { get; set; }
        public virtual campus_DOCENCIA campus_DOCENCIA { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
