//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_FORO
    {
        public long ID_Foro { get; set; }
        public long ID_Curso { get; set; }
        public long ID_Docencia_Grupo { get; set; }
        public Nullable<long> ID_Docencia_Subgrupo { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FAlta { get; set; }
        public Nullable<System.DateTime> FCierre { get; set; }
        public long ID_Moderador { get; set; }
    }
}
