//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CONTENIDO_DOCENCIA
    {
        public long ID_Contenido_Docencia { get; set; }
        public long ID_Docencia { get; set; }
        public long ID_Curso { get; set; }
        public long ID_Recurso { get; set; }
        public string COD_Curso { get; set; }
        public string COD_Recurso { get; set; }
        public decimal Sesion { get; set; }
        public Nullable<decimal> Lectura { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Visible { get; set; }
        public Nullable<System.DateTime> Fecha_Limite_Ord { get; set; }
        public string Comentarios_Ord { get; set; }
        public Nullable<System.DateTime> Fecha_Limite_Ext { get; set; }
        public string Comentarios_Ext { get; set; }
        public Nullable<System.DateTime> Fecha_Limite_Gra { get; set; }
        public string Comentarios_Gra { get; set; }
    }
}
