//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_FORO_RESPUESTA
    {
        public long ID_MsgR_Foro { get; set; }
        public string Titulo { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public long ID_Persona { get; set; }
        public long ID_Msg_Foro { get; set; }
        public long ID_Foro { get; set; }
        public string Borrador { get; set; }
        public Nullable<long> Resp_id_persona { get; set; }
        public Nullable<System.DateTime> Resp_fecha { get; set; }
    }
}
