//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampusCursoOnline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CampusCursoOnline()
        {
            this.OnlineCarrito = new HashSet<OnlineCarrito>();
            this.OnlineDeseo = new HashSet<OnlineDeseo>();
            this.OnlineOrdenProducto = new HashSet<OnlineOrdenProducto>();
        }
    
        public int Id { get; set; }
        public long CampusCursoId { get; set; }
        public Nullable<long> CampusDocenciaId { get; set; }
        public string QueAprenderas { get; set; }
        public string Requisitos { get; set; }
        public string AQuienVaDirigido { get; set; }
        public string Titulo { get; set; }
        public string SubTitulo { get; set; }
        public string Nivel { get; set; }
        public string Tags { get; set; }
        public string Imagen { get; set; }
        public string ImagenAlt { get; set; }
        public string Video { get; set; }
        public string VideoAlt { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaURL { get; set; }
        public int NumEstudiantes { get; set; }
        public int NumCalificaciones { get; set; }
        public double NumEstrellas { get; set; }
        public double PrecioMinimo { get; set; }
        public double PrecioRecomendado { get; set; }
        public double Precio { get; set; }
        public Nullable<double> PrecioOferta { get; set; }
        public string Descripcion { get; set; }
        public bool EnVenta { get; set; }
        public Nullable<long> IdiomasId { get; set; }
        public string MetaKeywords { get; set; }
        public int OnlineAfiliadoId { get; set; }
        public Nullable<System.DateTime> OfertaFechaFin { get; set; }
        public Nullable<System.DateTime> OfertaFechaInicio { get; set; }
        public Nullable<double> PrecioOfertaMin { get; set; }
    
        public virtual campus_CURSO campus_CURSO { get; set; }
        public virtual campus_DOCENCIA campus_DOCENCIA { get; set; }
        public virtual Idiomas Idiomas { get; set; }
        public virtual OnlineAfiliado OnlineAfiliado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineCarrito> OnlineCarrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineDeseo> OnlineDeseo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineOrdenProducto> OnlineOrdenProducto { get; set; }
    }
}
