//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CLIENTES_DOC
    {
        public long idClienteDoc { get; set; }
        public long idCliente { get; set; }
        public string tipo_documento { get; set; }
        public string Descripcion { get; set; }
        public string Fichero { get; set; }
        public Nullable<System.DateTime> fecha_caducidad { get; set; }
        public Nullable<long> id_docencia { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
