//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_ACL
    {
        public long idPersona { get; set; }
        public bool Ver_origenes { get; set; }
        public bool Todos_alumnos { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
