//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_AUTORIA
    {
        public long idAutoria { get; set; }
        public long idCurso { get; set; }
        public long idAutor { get; set; }
        public Nullable<decimal> Pct { get; set; }
        public Nullable<long> idRolDocente { get; set; }
    }
}
