//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_OPINIONES_SOLICITUD
    {
        public long id_solicitud_opinion { get; set; }
        public long id_docencia { get; set; }
        public int id_tso { get; set; }
        public System.DateTime fecha { get; set; }
        public string nombreFrom { get; set; }
        public string mailFrom { get; set; }
        public string replyTo { get; set; }
        public string asunto { get; set; }
        public string body { get; set; }
        public bool procesado { get; set; }
    }
}
