//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_REGLAS_AUTOMATIZACION
    {
        public long id_regla { get; set; }
        public int id_tipo { get; set; }
        public int orden { get; set; }
        public string estados { get; set; }
        public string origenes { get; set; }
        public string cursos { get; set; }
        public string paises { get; set; }
        public string acciones { get; set; }
        public Nullable<bool> fecha_all { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<bool> hora_all { get; set; }
        public string hora_inicio { get; set; }
        public string hora_fin { get; set; }
        public bool activo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    }
}
