//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_EDUCACION
    {
        public long ID_Educacion { get; set; }
        public long id_cliente { get; set; }
        public string Tipo_Programa { get; set; }
        public string Programa { get; set; }
        public Nullable<System.DateTime> Fecha_Convocatoria { get; set; }
        public Nullable<long> Nivel_Educativo { get; set; }
        public string Campo_Estudio { get; set; }
        public string Titulacion { get; set; }
        public string Centro { get; set; }
        public Nullable<long> Pais { get; set; }
        public string Poblacion { get; set; }
        public Nullable<long> Idioma { get; set; }
        public Nullable<System.DateTime> FInicio { get; set; }
        public Nullable<System.DateTime> FFin { get; set; }
        public string Observaciones { get; set; }
        public Nullable<long> Lang { get; set; }
        public Nullable<long> Nivel { get; set; }
        public string Observaciones_Lang { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
