//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CLIENTES_COMERCIAL
    {
        public long idCliente { get; set; }
        public long idPertenencia { get; set; }
        public string MailPertenencia { get; set; }
    
        public virtual campus_AUX campus_AUX { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
