//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_WORKFLOW_DOCENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campus_WORKFLOW_DOCENCIA()
        {
            this.campus_WORKFLOW_GRUPO = new HashSet<campus_WORKFLOW_GRUPO>();
        }
    
        public long id_WF_Docencia { get; set; }
        public long id_Programa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_WORKFLOW_GRUPO> campus_WORKFLOW_GRUPO { get; set; }
    }
}
