//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_LH
    {
        public long idLH { get; set; }
        public System.DateTime Fecha { get; set; }
        public long idPersona { get; set; }
        public decimal Importe { get; set; }
        public string LH { get; set; }
        public string Comentarios { get; set; }
        public int Online { get; set; }
        public Nullable<long> idCoste { get; set; }
    }
}
