//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_AUX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campus_AUX()
        {
            this.campus_CLIENTES_COMERCIAL = new HashSet<campus_CLIENTES_COMERCIAL>();
            this.Test_Triada_Cerebral = new HashSet<Test_Triada_Cerebral>();
            this.Test_Triada_Cerebral1 = new HashSet<Test_Triada_Cerebral>();
            this.Test_Triada_Cerebral2 = new HashSet<Test_Triada_Cerebral>();
        }
    
        public long ID_Aux { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Tabla { get; set; }
        public Nullable<decimal> Activo { get; set; }
        public Nullable<bool> Img { get; set; }
        public Nullable<int> Pasos { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> No_Visible_Informes { get; set; }
        public string PlantillaMail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_CLIENTES_COMERCIAL> campus_CLIENTES_COMERCIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Triada_Cerebral> Test_Triada_Cerebral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Triada_Cerebral> Test_Triada_Cerebral1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Triada_Cerebral> Test_Triada_Cerebral2 { get; set; }
    }
}
