//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_DOCENCIA_SUBGRUPO
    {
        public long ID_Docencia_Subgrupo { get; set; }
        public long ID_Docencia { get; set; }
        public long ID_Persona { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    }
}
