//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_TUTORIA
    {
        public long idTutoria { get; set; }
        public long idDocencia { get; set; }
        public long idCurso { get; set; }
        public long idTutor { get; set; }
        public Nullable<long> idRolDocente { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Pct { get; set; }
        public Nullable<bool> Auto { get; set; }
        public Nullable<int> Estado { get; set; }
        public string ord_acta_fich { get; set; }
        public Nullable<System.DateTime> ord_acta_fecha { get; set; }
        public string ext_acta_fich { get; set; }
        public Nullable<System.DateTime> ext_acta_fecha { get; set; }
        public string gra_acta_fich { get; set; }
        public Nullable<System.DateTime> gra_acta_fecha { get; set; }
        public string fin_acta_fich { get; set; }
        public Nullable<System.DateTime> fin_acta_fecha { get; set; }
        public string file_planificacion { get; set; }
    }
}
