//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CONTENIDO_CURSO
    {
        public long ID_Contenido_Curso { get; set; }
        public long ID_Curso { get; set; }
        public long ID_Recurso { get; set; }
        public string COD_Curso { get; set; }
        public string COD_Recurso { get; set; }
        public int Sesion { get; set; }
        public int Lectura { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
