//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campus_CURSO_EXAMEN
    {
        public long ID_Curso_Examen { get; set; }
        public string Titulo { get; set; }
        public string Normas { get; set; }
        public string Comentarios { get; set; }
        public long ID_Curso { get; set; }
        public Nullable<int> Num_Preguntas { get; set; }
        public Nullable<int> Num_Respuestas { get; set; }
        public Nullable<int> Apto { get; set; }
        public int Minutos { get; set; }
        public Nullable<bool> AutoCorregir { get; set; }
        public Nullable<int> Num_Realizados { get; set; }
        public Nullable<int> Num_Aptos { get; set; }
        public Nullable<decimal> Nota_Media { get; set; }
    }
}
