//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carritos
    {
        public long id_carrito { get; set; }
        public long id_producto { get; set; }
        public Nullable<long> id_cliente { get; set; }
        public string cookie { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int Numero_Unidades { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
