//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA_CAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIA_CAT()
        {
            this.BLOG_USU = new HashSet<BLOG_USU>();
            this.SUBCATEGORIA_SBC = new HashSet<SUBCATEGORIA_SBC>();
            this.SUSCRIPCION_SCR = new HashSet<SUSCRIPCION_SCR>();
        }
    
        public int CAT_ID { get; set; }
        public string CAT_NOMBRE { get; set; }
        public string CAT_IMAGEN { get; set; }
        public string CAT_DESCRIPCION { get; set; }
        public int CAT_CAPTCHA { get; set; }
        public string CAT_KEYWORDS { get; set; }
        public int CAT_PERMITE_CMT { get; set; }
        public int CAT_USU_ALTA { get; set; }
        public Nullable<int> CAT_CONFIRMACION_CMT { get; set; }
        public string CAT_AUTOR_DEFECTO { get; set; }
        public string CAT_PUBLICIDAD_SUP { get; set; }
        public string CAT_PUBLICIDAD_LAT1 { get; set; }
        public string CAT_PUBLICIDAD_LAT2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOG_USU> BLOG_USU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBCATEGORIA_SBC> SUBCATEGORIA_SBC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUSCRIPCION_SCR> SUSCRIPCION_SCR { get; set; }
    }
}
