//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES()
        {
            this.AspNetUsers = new HashSet<AspNetUsers>();
            this.BEC_SOLICITUD_BECA = new HashSet<BEC_SOLICITUD_BECA>();
            this.campus_CLIENTES_COMERCIAL = new HashSet<campus_CLIENTES_COMERCIAL>();
            this.campus_CLIENTES_DOC = new HashSet<campus_CLIENTES_DOC>();
            this.campus_DOCENCIA_GRUPO_REC_PRACT = new HashSet<campus_DOCENCIA_GRUPO_REC_PRACT>();
            this.campus_EDUCACION = new HashSet<campus_EDUCACION>();
            this.campus_ENCUESTA = new HashSet<campus_ENCUESTA>();
            this.campus_EXPERIENCIA_PROFESIONAL = new HashSet<campus_EXPERIENCIA_PROFESIONAL>();
            this.campus_OTROS = new HashSet<campus_OTROS>();
            this.Carritos = new HashSet<Carritos>();
            this.CLIENTES_COMENTARIOS = new HashSet<CLIENTES_COMENTARIOS>();
            this.EDU_Suscriptores = new HashSet<EDU_Suscriptores>();
            this.OnlineCarrito = new HashSet<OnlineCarrito>();
            this.OnlineDeseo = new HashSet<OnlineDeseo>();
            this.OnlineOrden = new HashSet<OnlineOrden>();
            this.Pedidos = new HashSet<Pedidos>();
            this.sbs_TP_Contrato = new HashSet<sbs_TP_Contrato>();
            this.OnlineAfiliado = new HashSet<OnlineAfiliado>();
        }
    
        public long id_cliente { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string Nombre_Completo { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public string Lugar_nac { get; set; }
        public string sexo { get; set; }
        public string nif { get; set; }
        public string pasaporte { get; set; }
        public string telefono { get; set; }
        public string telefono_contacto { get; set; }
        public string Fax { get; set; }
        public string email { get; set; }
        public string Email2 { get; set; }
        public string tipo_via { get; set; }
        public string via { get; set; }
        public string numero { get; set; }
        public string escalera { get; set; }
        public string piso { get; set; }
        public string puerta { get; set; }
        public string cp { get; set; }
        public string localidad { get; set; }
        public Nullable<long> id_provincia { get; set; }
        public Nullable<long> id_pais { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_activacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public string activo { get; set; }
        public Nullable<long> id_idioma { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string pregunta { get; set; }
        public string respuesta { get; set; }
        public Nullable<int> id_tipo_conocimiento_web { get; set; }
        public string Foto { get; set; }
        public Nullable<System.DateTime> FCodEtico { get; set; }
        public string Profesor { get; set; }
        public string Administrador { get; set; }
        public Nullable<bool> Comercial { get; set; }
        public Nullable<bool> SuperAdministrador { get; set; }
        public string Biografia { get; set; }
        public string Notas { get; set; }
        public Nullable<int> Nivel_Estudios { get; set; }
        public Nullable<int> Experiencia { get; set; }
        public string Sector_Profesional { get; set; }
        public Nullable<int> Situacion_Actual { get; set; }
        public string Comentarios_Internos { get; set; }
        public string Ficha { get; set; }
        public string Cargo { get; set; }
        public string Empresa { get; set; }
        public string Key { get; set; }
        public Nullable<bool> AutoMarketing { get; set; }
        public Nullable<long> scoring { get; set; }
        public string skype { get; set; }
        public string Encuesta { get; set; }
        public Nullable<bool> online { get; set; }
        public string descripcion_ficha_base { get; set; }
        public Nullable<bool> practicas { get; set; }
        public bool IsAffiliate { get; set; }
        public Nullable<bool> Baja_Impago { get; set; }
        public string comentario_publico_alumno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BEC_SOLICITUD_BECA> BEC_SOLICITUD_BECA { get; set; }
        public virtual campus_ACL campus_ACL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_CLIENTES_COMERCIAL> campus_CLIENTES_COMERCIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_CLIENTES_DOC> campus_CLIENTES_DOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_DOCENCIA_GRUPO_REC_PRACT> campus_DOCENCIA_GRUPO_REC_PRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_EDUCACION> campus_EDUCACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_ENCUESTA> campus_ENCUESTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_EXPERIENCIA_PROFESIONAL> campus_EXPERIENCIA_PROFESIONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campus_OTROS> campus_OTROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carritos> Carritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTES_COMENTARIOS> CLIENTES_COMENTARIOS { get; set; }
        public virtual Idiomas Idiomas { get; set; }
        public virtual Paises Paises { get; set; }
        public virtual Provincias Provincias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDU_Suscriptores> EDU_Suscriptores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineCarrito> OnlineCarrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineDeseo> OnlineDeseo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineOrden> OnlineOrden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sbs_TP_Contrato> sbs_TP_Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineAfiliado> OnlineAfiliado { get; set; }
    }
}
