//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMENTARIOS_CMT
    {
        public int CMT_ID { get; set; }
        public string CMT_NOMBRE { get; set; }
        public string CMT_MAIL { get; set; }
        public string CMT_COMENTARIO { get; set; }
        public System.DateTime CMT_FECHA { get; set; }
        public Nullable<float> CMT_VALORACION { get; set; }
        public Nullable<int> CMT_ESTADO { get; set; }
        public Nullable<int> CMT_IDNOTICIA { get; set; }
        public Nullable<int> CMT_PARID { get; set; }
    
        public virtual NOTICIAS_NOT NOTICIAS_NOT { get; set; }
        public virtual PAR_PARTICIPANTES PAR_PARTICIPANTES { get; set; }
    }
}
