//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVE_PETICION
    {
        public long idCVE { get; set; }
        public long idUsuario { get; set; }
        public long idDocencia { get; set; }
        public long idCurso { get; set; }
        public System.DateTime fecha_peticion { get; set; }
        public Nullable<bool> mail_send { get; set; }
        public bool process { get; set; }
    }
}
