//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVE_PETICION
    {
        public long idCVE { get; set; }
        public long idUsuario { get; set; }
        public long idDocencia { get; set; }
        public long idCurso { get; set; }
        public System.DateTime fecha_peticion { get; set; }
        public Nullable<bool> mail_send { get; set; }
        public bool process { get; set; }
    }
}
