//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVE_CERTIFICADO
    {
        public string CVE { get; set; }
        public long idPersona { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Titulo { get; set; }
        public string Expedido_Por { get; set; }
        public string Comentarios { get; set; }
        public Nullable<long> idCurso { get; set; }
    }
}
