//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public long id_direccion { get; set; }
        public long id_cliente { get; set; }
        public string tipo_via { get; set; }
        public string via { get; set; }
        public string numero { get; set; }
        public string escalera { get; set; }
        public string piso { get; set; }
        public string puerta { get; set; }
        public string cp { get; set; }
        public string localidad { get; set; }
        public long id_provincia { get; set; }
        public long id_pais { get; set; }
        public Nullable<long> Tipo { get; set; }
    }
}
