//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDU_Banners
    {
        public long Id_Banner { get; set; }
        public long Id_Edu_Producto { get; set; }
        public string Nombre { get; set; }
        public string Banner { get; set; }
        public string Banner_2x { get; set; }
        public int Orden { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public string Link { get; set; }
    
        public virtual EDU_Productos EDU_Productos { get; set; }
    }
}
