//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDU_Banners
    {
        public long Id_Banner { get; set; }
        public long Id_Edu_Producto { get; set; }
        public string Nombre { get; set; }
        public string Banner { get; set; }
        public string Banner_2x { get; set; }
        public int Orden { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public string Link { get; set; }
    
        public virtual EDU_Productos EDU_Productos { get; set; }
    }
}
