//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDU_Suscriptores
    {
        public long Id_Edu_Producto { get; set; }
        public long Id_Persona { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public decimal Importe { get; set; }
        public string Comentarios { get; set; }
        public Nullable<long> IdPedido { get; set; }
        public bool Activo { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual EDU_Productos EDU_Productos { get; set; }
    }
}
