//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_CAMPAIGNS
    {
        public long id_camp { get; set; }
        public string nombre { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> num_suscriptores { get; set; }
        public Nullable<int> num_envios { get; set; }
        public Nullable<int> num_opens { get; set; }
        public Nullable<int> num_bounced { get; set; }
        public Nullable<int> num_clics { get; set; }
        public System.DateTime fecha_scheduled { get; set; }
        public Nullable<decimal> pct_opens { get; set; }
        public Nullable<decimal> pct_envios { get; set; }
        public Nullable<decimal> pct_bounced { get; set; }
        public Nullable<decimal> pct_scheduled { get; set; }
        public Nullable<decimal> pct_clicks { get; set; }
        public Nullable<int> num_unsubscribe { get; set; }
        public Nullable<decimal> pct_unsubscribe { get; set; }
        public int priority { get; set; }
        public string mailFrom { get; set; }
        public string nombreFrom { get; set; }
        public string replyTo { get; set; }
        public string asunto { get; set; }
        public string body { get; set; }
        public string adjuntos { get; set; }
        public Nullable<long> id_camp_relacionada { get; set; }
        public Nullable<long> id_els { get; set; }
        public Nullable<long> id_landing { get; set; }
        public string tags { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<bool> newsletter { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> fecha_act { get; set; }
        public string tags_clic { get; set; }
    }
}
