//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_SERVER_STATUS
    {
        public int id_ess { get; set; }
        public int id_es { get; set; }
        public System.DateTime fecha { get; set; }
        public int num_envios { get; set; }
        public bool bloqueado { get; set; }
    
        public virtual EMAIL_SERVER EMAIL_SERVER { get; set; }
    }
}
