//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_SUSCRIPCIONES
    {
        public long id_s { get; set; }
        public long id_els { get; set; }
        public string nombre_completo { get; set; }
        public string mail { get; set; }
        public long id_alumno { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
    }
}
