//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_SERVER_ESTADISTICAS
    {
        public long id_esh { get; set; }
        public int id_es { get; set; }
        public int year { get; set; }
        public string type { get; set; }
        public int data { get; set; }
        public Nullable<long> id_usuario { get; set; }
    
        public virtual EMAIL_SERVER EMAIL_SERVER { get; set; }
    }
}
