//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_ACTIVADORES
    {
        public long id_activador { get; set; }
        public int tipo { get; set; }
        public int reintento { get; set; }
        public long id_camp { get; set; }
        public System.DateTime fecha_act { get; set; }
        public int priority { get; set; }
        public string nombreFrom { get; set; }
        public string mailFrom { get; set; }
        public string replyTo { get; set; }
        public string asunto { get; set; }
        public string body { get; set; }
        public string adjuntos { get; set; }
        public Nullable<int> data_bajas { get; set; }
        public Nullable<int> data_opens { get; set; }
        public Nullable<int> data_clics { get; set; }
        public Nullable<int> data_users { get; set; }
        public Nullable<bool> procesado { get; set; }
    }
}
