//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_CAMPAIGNS_STATUS
    {
        public long id_ecs { get; set; }
        public long id_camp { get; set; }
        public long id_s { get; set; }
        public long id_ec { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> fecha_open { get; set; }
        public Nullable<long> id_ecs_reenv { get; set; }
        public Nullable<bool> reenvio { get; set; }
        public Nullable<bool> procesado { get; set; }
    }
}
