//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_LISTADO_SUSCRIPCIONES
    {
        public long id_els { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<int> num_total { get; set; }
        public Nullable<int> num_actual { get; set; }
        public Nullable<int> num_bajas { get; set; }
        public string historico { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<bool> auto { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public string sql { get; set; }
    }
}
