//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_SERVER_STATUS
    {
        public int id_ess { get; set; }
        public int id_es { get; set; }
        public System.DateTime fecha { get; set; }
        public int num_envios { get; set; }
        public bool bloqueado { get; set; }
    
        public virtual EMAIL_SERVER EMAIL_SERVER { get; set; }
    }
}
