//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_LISTADO_SUSCRIPCIONES
    {
        public long id_els { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<int> num_total { get; set; }
        public Nullable<int> num_actual { get; set; }
        public Nullable<int> num_bajas { get; set; }
        public string historico { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<bool> auto { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public string sql { get; set; }
    }
}
