//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_CONTENT
    {
        public long id_ec { get; set; }
        public string nombreTo { get; set; }
        public string mailTo { get; set; }
        public Nullable<System.DateTime> date_schedule { get; set; }
        public int priority { get; set; }
        public string nombreFrom { get; set; }
        public string mailFrom { get; set; }
        public string replyTo { get; set; }
        public string mailCCO { get; set; }
        public string asunto { get; set; }
        public string body { get; set; }
        public string adjuntos { get; set; }
        public Nullable<System.DateTime> date_send { get; set; }
        public Nullable<int> id_es { get; set; }
        public Nullable<long> message_ID { get; set; }
        public string status { get; set; }
        public string mail_data { get; set; }
        public Nullable<long> id_os { get; set; }
    }
}
