//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_SERVER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMAIL_SERVER()
        {
            this.EMAIL_SERVER_ESTADISTICAS = new HashSet<EMAIL_SERVER_ESTADISTICAS>();
            this.EMAIL_SERVER_STATUS = new HashSet<EMAIL_SERVER_STATUS>();
        }
    
        public int id_es { get; set; }
        public string identificador { get; set; }
        public string servidor { get; set; }
        public int puerto { get; set; }
        public bool ssl { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string nombreFrom { get; set; }
        public string mailCCO { get; set; }
        public Nullable<int> limite { get; set; }
        public Nullable<int> limite_mes { get; set; }
        public Nullable<int> limite_anyo { get; set; }
        public Nullable<int> fecha_inicio_dia { get; set; }
        public Nullable<int> fecha_inicio_mes { get; set; }
        public string replyTo { get; set; }
        public bool activo { get; set; }
        public bool visible { get; set; }
        public bool prioritario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAIL_SERVER_ESTADISTICAS> EMAIL_SERVER_ESTADISTICAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAIL_SERVER_STATUS> EMAIL_SERVER_STATUS { get; set; }
    }
}
