//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enc_ALUMNIO
    {
        public System.DateTime Fecha { get; set; }
        public int IdEncuesta { get; set; }
        public Nullable<decimal> IdDocencia { get; set; }
        public Nullable<decimal> IdCurso { get; set; }
        public Nullable<decimal> IdPersona { get; set; }
        public decimal IdPregunta { get; set; }
        public string PreguntaValor { get; set; }
    }
}
