//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enc_ENCUESTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enc_ENCUESTA()
        {
            this.enc_PREGUNTA = new HashSet<enc_PREGUNTA>();
        }
    
        public int ID_ENCUESTA { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FAlta { get; set; }
        public Nullable<System.DateTime> FBaja { get; set; }
        public string Descripción { get; set; }
        public string Comentarios_internos { get; set; }
        public byte[] Codigo_inteno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enc_PREGUNTA> enc_PREGUNTA { get; set; }
    }
}
