//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enc_ALUMNIO
    {
        public System.DateTime Fecha { get; set; }
        public int IdEncuesta { get; set; }
        public Nullable<decimal> IdDocencia { get; set; }
        public Nullable<decimal> IdCurso { get; set; }
        public Nullable<decimal> IdPersona { get; set; }
        public decimal IdPregunta { get; set; }
        public string PreguntaValor { get; set; }
    }
}
