//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enc_PREGUNTA
    {
        public decimal ID_PREGUNTA { get; set; }
        public int IdEncuesta { get; set; }
        public System.DateTime FAlta { get; set; }
        public Nullable<System.DateTime> FBaja { get; set; }
        public string Pregunta { get; set; }
        public int IdTipoPregunta { get; set; }
        public Nullable<bool> Obligatoria { get; set; }
        public string CodigoPregunta { get; set; }
    
        public virtual enc_ENCUESTA enc_ENCUESTA { get; set; }
    }
}
