//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTOS
    {
        public long Id_Evento { get; set; }
        public string Nombre { get; set; }
        public string Url { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Empresa_Organizadora { get; set; }
        public string Descripcion { get; set; }
        public string Donde { get; set; }
        public string Horario { get; set; }
    }
}
