//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPERTOS_CARACTERISTICAS
    {
        public long Id_Experto { get; set; }
        public Nullable<long> Id_Curso { get; set; }
        public bool Principal { get; set; }
        public int Consejo { get; set; }
        public long ID_EC { get; set; }
    }
}
