//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPERTOS
    {
        public long Id_Experto { get; set; }
        public string Nombre { get; set; }
        public string Foto { get; set; }
        public string Cargo { get; set; }
        public string Comentario { get; set; }
        public string Url_Twitter { get; set; }
        public string Url_Linkedin { get; set; }
        public Nullable<long> Id_Curso { get; set; }
        public Nullable<decimal> Principal { get; set; }
        public Nullable<decimal> Consejo { get; set; }
        public string CV { get; set; }
        public string Foto_Original { get; set; }
        public string Acuerdo { get; set; }
        public Nullable<long> Usuario { get; set; }
        public string Mail { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Video { get; set; }
        public string CCC { get; set; }
        public Nullable<decimal> Pct_autor { get; set; }
        public Nullable<decimal> Pct_tutor { get; set; }
        public Nullable<decimal> Eur_presencial { get; set; }
        public string Datos_facturacion { get; set; }
        public string Nif_Cif { get; set; }
        public Nullable<System.DateTime> Fecha_convenio { get; set; }
        public string Foto2x { get; set; }
        public string Meta_Url { get; set; }
        public Nullable<decimal> Eur_online { get; set; }
        public string Url_Disco { get; set; }
    }
}
