//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHERO_FIC
    {
        public int FIC_ID { get; set; }
        public Nullable<int> FIC_IDNOT { get; set; }
        public string FIC_RUTA { get; set; }
        public string FIC_NOMBRE { get; set; }
    
        public virtual NOTICIAS_NOT NOTICIAS_NOT { get; set; }
    }
}
