//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOT_FOTOGRAFIA
    {
        public int Fot_Id { get; set; }
        public Nullable<int> Gal_Id { get; set; }
        public string Fot_Nombre { get; set; }
        public string Fot_Descripcion { get; set; }
        public string Fot_Foto_Mini { get; set; }
        public string Fot_Foto_Maxi { get; set; }
        public Nullable<int> Fot_Activo { get; set; }
        public Nullable<int> Fot_Tipo { get; set; }
        public string Fot_Video { get; set; }
    
        public virtual GAL_GALERIA GAL_GALERIA { get; set; }
    }
}
