//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_GALERIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAL_GALERIA()
        {
            this.FOT_FOTOGRAFIA = new HashSet<FOT_FOTOGRAFIA>();
        }
    
        public int Gal_Id { get; set; }
        public string Gal_Nombre { get; set; }
        public string Gal_Descripcion { get; set; }
        public Nullable<int> Gal_Tipo { get; set; }
        public Nullable<int> Gal_Activo { get; set; }
        public string Gal_Foto_Principal { get; set; }
        public string Gal_DescFicha { get; set; }
        public Nullable<int> Gal_Categoria { get; set; }
        public Nullable<int> Gal_Subcategoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOT_FOTOGRAFIA> FOT_FOTOGRAFIA { get; set; }
    }
}
