//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_GALERIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAL_GALERIA()
        {
            this.FOT_FOTOGRAFIA = new HashSet<FOT_FOTOGRAFIA>();
        }
    
        public int Gal_Id { get; set; }
        public string Gal_Nombre { get; set; }
        public string Gal_Descripcion { get; set; }
        public Nullable<int> Gal_Tipo { get; set; }
        public Nullable<int> Gal_Activo { get; set; }
        public string Gal_Foto_Principal { get; set; }
        public string Gal_DescFicha { get; set; }
        public Nullable<int> Gal_Categoria { get; set; }
        public Nullable<int> Gal_Subcategoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOT_FOTOGRAFIA> FOT_FOTOGRAFIA { get; set; }
    }
}
