//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gastos_envio
    {
        public long id_gastos_envio { get; set; }
        public Nullable<long> id_provincia { get; set; }
        public long id_pais { get; set; }
        public Nullable<long> peso_min { get; set; }
        public Nullable<long> peso_max { get; set; }
        public Nullable<long> volumen_min { get; set; }
        public Nullable<long> volumen_max { get; set; }
        public decimal precio { get; set; }
    
        public virtual Paises Paises { get; set; }
        public virtual Provincias Provincias { get; set; }
    }
}
