//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEO_IP
    {
        public string ip { get; set; }
        public string loc { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public string country { get; set; }
        public Nullable<int> id_pais { get; set; }
        public System.DateTime fecha_act { get; set; }
        public Nullable<bool> procesado { get; set; }
    }
}
