//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_AUX
    {
        public int id_inf_aux { get; set; }
        public string Tabla { get; set; }
        public string Tabla_padre { get; set; }
        public string Valor { get; set; }
        public Nullable<int> ID_Padre { get; set; }
    }
}
