//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_MK_OBJETIVOS
    {
        public long id { get; set; }
        public int Año { get; set; }
        public string Periodo { get; set; }
        public string Tipo { get; set; }
        public decimal Obj_EUR { get; set; }
        public int Obj_UN { get; set; }
        public Nullable<decimal> Real_EUR { get; set; }
        public Nullable<int> Real_UN { get; set; }
        public Nullable<System.DateTime> Real_UltAct { get; set; }
    }
}
