//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_FIN_SUBAREAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INF_FIN_SUBAREAS()
        {
            this.INF_FIN_SUBAREAS2 = new HashSet<INF_FIN_SUBAREAS2>();
        }
    
        public int ID { get; set; }
        public int AreaID { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
        public int Orden { get; set; }
        public Nullable<bool> TieneHijos { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual INF_FIN_AREAS INF_FIN_AREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INF_FIN_SUBAREAS2> INF_FIN_SUBAREAS2 { get; set; }
    }
}
