//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_MK_DATA
    {
        public decimal id { get; set; }
        public string Ano { get; set; }
        public string Mes { get; set; }
        public Nullable<decimal> Eur_Inversion { get; set; }
        public Nullable<int> id_mk_medio { get; set; }
        public Nullable<int> id_mk_tipo { get; set; }
        public Nullable<int> clics { get; set; }
        public Nullable<int> leads_origen { get; set; }
        public Nullable<int> matriculas { get; set; }
        public Nullable<decimal> Eur_Ventas { get; set; }
        public string Comentarios { get; set; }
        public Nullable<bool> Facturacion_ok { get; set; }
        public Nullable<int> leads_ok { get; set; }
    }
}
