//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_FIN_FACTURAS
    {
        public long idInfFinFacturas { get; set; }
        public string sociedad { get; set; }
        public int numero { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public string cliente_nombre { get; set; }
        public string cliente_nif { get; set; }
        public string descripcion { get; set; }
        public decimal eur_pvp { get; set; }
        public decimal eur_beca { get; set; }
        public decimal eur_dto { get; set; }
        public decimal eur_precio { get; set; }
        public decimal eur_fundacion { get; set; }
        public decimal eur_universidad { get; set; }
        public decimal eur_tripartita { get; set; }
        public decimal eur_iva { get; set; }
        public decimal eur_irpf { get; set; }
        public decimal eur_total { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public Nullable<System.DateTime> fecha_cobro { get; set; }
        public string comentarios { get; set; }
        public string atribucion { get; set; }
        public string fichero { get; set; }
    }
}
