//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_FIN_COSTES
    {
        public long IdInfFinCostes { get; set; }
        public string Sociedad { get; set; }
        public int NumSecuencia { get; set; }
        public System.DateTime FEmision { get; set; }
        public string EmpresaNombre { get; set; }
        public string EmpresaCIF { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> SubArea { get; set; }
        public Nullable<int> SubArea2 { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> IRPF { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> FPago { get; set; }
        public string ApunteBanco { get; set; }
        public Nullable<bool> NoFactura { get; set; }
        public string Comentarios { get; set; }
        public string Trimestre { get; set; }
        public string Fichero { get; set; }
        public Nullable<bool> Provision { get; set; }
        public Nullable<bool> Tax { get; set; }
        public string Tax_type { get; set; }
    }
}
