//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_FIN_SUBAREAS2
    {
        public int ID { get; set; }
        public int SubareaID { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
        public int Orden { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual INF_FIN_SUBAREAS INF_FIN_SUBAREAS { get; set; }
    }
}
