//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_FIN_SUBAREAS2
    {
        public int ID { get; set; }
        public int SubareaID { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
        public int Orden { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual INF_FIN_SUBAREAS INF_FIN_SUBAREAS { get; set; }
    }
}
