//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineas_pedido
    {
        public long id_linea_pedido { get; set; }
        public long id_pedido { get; set; }
        public decimal precio { get; set; }
        public decimal iva { get; set; }
        public Nullable<System.DateTime> fecha_devolucion { get; set; }
        public string motivo_devolucion { get; set; }
        public long id_producto { get; set; }
        public Nullable<decimal> oferta_descuento { get; set; }
        public Nullable<decimal> precio_total { get; set; }
        public int Numero_Unidades { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
    }
}
