//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineas_pedido
    {
        public long id_linea_pedido { get; set; }
        public long id_pedido { get; set; }
        public decimal precio { get; set; }
        public decimal iva { get; set; }
        public Nullable<System.DateTime> fecha_devolucion { get; set; }
        public string motivo_devolucion { get; set; }
        public long id_producto { get; set; }
        public Nullable<decimal> oferta_descuento { get; set; }
        public Nullable<decimal> precio_total { get; set; }
        public int Numero_Unidades { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
    }
}
