//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIAS_RELACION_REL
    {
        public int REL_ID1 { get; set; }
        public int REL_ID2 { get; set; }
        public int REL_TIPO { get; set; }
    
        public virtual TIPOS_RELACION TIPOS_RELACION { get; set; }
    }
}
