//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIAS_NOT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTICIAS_NOT()
        {
            this.COMENTARIOS_CMT = new HashSet<COMENTARIOS_CMT>();
            this.FICHERO_FIC = new HashSet<FICHERO_FIC>();
            this.URL_URL = new HashSet<URL_URL>();
            this.VIDEOS_VID = new HashSet<VIDEOS_VID>();
        }
    
        public int NOT_ID { get; set; }
        public int NOT_IDCATEGORIA { get; set; }
        public Nullable<System.DateTime> NOT_FECHA { get; set; }
        public string NOT_TITULO { get; set; }
        public string NOT_DESC_CORTA { get; set; }
        public string NOT_CUERPO { get; set; }
        public string NOT_FOTO_PORTADA { get; set; }
        public string NOT_PIE_FOTOP { get; set; }
        public string NOT_CINTILLO { get; set; }
        public Nullable<int> NOT_PUBLICABLE { get; set; }
        public string NOT_AUTOR { get; set; }
        public Nullable<int> NOT_N_COMENTARIOS { get; set; }
        public int NOT_PERMITE_CMT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMENTARIOS_CMT> COMENTARIOS_CMT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHERO_FIC> FICHERO_FIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<URL_URL> URL_URL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIDEOS_VID> VIDEOS_VID { get; set; }
    }
}
