//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIAS_RELACION_REL
    {
        public int REL_ID1 { get; set; }
        public int REL_ID2 { get; set; }
        public int REL_TIPO { get; set; }
    
        public virtual TIPOS_RELACION TIPOS_RELACION { get; set; }
    }
}
