//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFF_sbs_Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OFF_sbs_Empresa()
        {
            this.OFF_sbs_Contacto = new HashSet<OFF_sbs_Contacto>();
            this.OFF_sbs_Empleo = new HashSet<OFF_sbs_Empleo>();
            this.OFF_sbs_Practicas = new HashSet<OFF_sbs_Practicas>();
            this.sbs_TP_Contrato = new HashSet<sbs_TP_Contrato>();
        }
    
        public long idEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string Cif { get; set; }
        public string Direccion { get; set; }
        public string Mail { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaConvenio { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string FicheroConvenio { get; set; }
        public string Comentarios { get; set; }
        public string Logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFF_sbs_Contacto> OFF_sbs_Contacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFF_sbs_Empleo> OFF_sbs_Empleo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFF_sbs_Practicas> OFF_sbs_Practicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sbs_TP_Contrato> sbs_TP_Contrato { get; set; }
    }
}
