//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFF_sbs_Empleo
    {
        public long idEmpleo { get; set; }
        public long idEmpresa { get; set; }
        public long idAlumno { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string Contrato { get; set; }
        public string Comentarios { get; set; }
    
        public virtual OFF_sbs_Empresa OFF_sbs_Empresa { get; set; }
    }
}
