//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFF_sbs_Practicas
    {
        public long idPractica { get; set; }
        public long idEmpresa { get; set; }
        public long idAlumno { get; set; }
        public long idCurso { get; set; }
        public long idTutorEmpresa { get; set; }
        public long idTutorEscuela { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public int Duracion { get; set; }
        public decimal AyudaEstudioMes { get; set; }
        public int HoraSemana { get; set; }
        public string FicheroAnexo { get; set; }
        public string Comentarios { get; set; }
    
        public virtual OFF_sbs_Empresa OFF_sbs_Empresa { get; set; }
    }
}
