//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineBusqueda
    {
        public long Id { get; set; }
        public string Query { get; set; }
        public string CategoriaIds { get; set; }
        public string SubCategoriaIds { get; set; }
        public string Niveles { get; set; }
        public int NumeroResultados { get; set; }
        public string Cookie { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Usuario { get; set; }
    }
}
