//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineOrdenProducto
    {
        public int Id { get; set; }
        public Nullable<int> ShoppingOrderId { get; set; }
        public double PrecioVenta { get; set; }
        public Nullable<int> CampusCursoOnlineId { get; set; }
    
        public virtual CampusCursoOnline CampusCursoOnline { get; set; }
        public virtual OnlineOrden OnlineOrden { get; set; }
    }
}
