//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineOrden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineOrden()
        {
            this.OnlineOrdenProducto = new HashSet<OnlineOrdenProducto>();
        }
    
        public int Id { get; set; }
        public System.DateTime ShoppingOrderDate { get; set; }
        public int OnlineStatusId { get; set; }
        public string CodigoMoneda { get; set; }
        public string MetodoPago { get; set; }
        public bool Reembolso { get; set; }
        public long ClientesId { get; set; }
        public int OnlineAfiliadoId { get; set; }
        public double OrdenAfiliadoComision { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual OnlineAfiliado OnlineAfiliado { get; set; }
        public virtual OnlineOrdenStatus OnlineOrdenStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineOrdenProducto> OnlineOrdenProducto { get; set; }
    }
}
