//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineOrdenProducto
    {
        public int Id { get; set; }
        public Nullable<int> ShoppingOrderId { get; set; }
        public double PrecioVenta { get; set; }
        public Nullable<int> CampusCursoOnlineId { get; set; }
    
        public virtual CampusCursoOnline CampusCursoOnline { get; set; }
        public virtual OnlineOrden OnlineOrden { get; set; }
    }
}
