//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public long id_pago { get; set; }
        public long id_pedido { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public long id_modo_pago { get; set; }
        public Nullable<decimal> sobreprecio { get; set; }
        public Nullable<decimal> gastos_envio { get; set; }
        public Nullable<decimal> importe { get; set; }
        public string num_factura { get; set; }
        public string aceptado { get; set; }
        public Nullable<decimal> oferta_gastos { get; set; }
        public Nullable<bool> procesado { get; set; }
    
        public virtual Modos_pago Modos_pago { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
