//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR_PARTICIPANTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAR_PARTICIPANTES()
        {
            this.COMENTARIOS_CMT = new HashSet<COMENTARIOS_CMT>();
        }
    
        public int PAR_ID { get; set; }
        public string PAR_EMAIL { get; set; }
        public Nullable<System.DateTime> PAR_FECHA { get; set; }
        public Nullable<int> PAR_CONFIRMADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMENTARIOS_CMT> COMENTARIOS_CMT { get; set; }
    }
}
