//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.Incidencias = new HashSet<Incidencias>();
            this.Lineas_pedido = new HashSet<Lineas_pedido>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public long id_pedido { get; set; }
        public long id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_pedido { get; set; }
        public string num_pedido { get; set; }
        public string tipo_via { get; set; }
        public string via { get; set; }
        public string numero { get; set; }
        public string escalera { get; set; }
        public string piso { get; set; }
        public string puerta { get; set; }
        public string cp { get; set; }
        public string localidad { get; set; }
        public long id_provincia { get; set; }
        public long id_pais { get; set; }
        public string observaciones { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidencias> Incidencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lineas_pedido> Lineas_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual Paises Paises { get; set; }
        public virtual Provincias Provincias { get; set; }
    }
}
