//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRA_EMPLEO
    {
        public long idEmpleo { get; set; }
        public long idEmpresa { get; set; }
        public long idAlumno { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string Contrato { get; set; }
        public string Comentarios { get; set; }
    
        public virtual PRA_EMPRESA PRA_EMPRESA { get; set; }
    }
}
