//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRA_CANDIDATOS
    {
        public long idCandidato { get; set; }
        public long idSolicitud { get; set; }
        public long idPersona { get; set; }
        public System.DateTime fecha { get; set; }
        public string comentarios { get; set; }
    
        public virtual PRA_SOLICITUD_PRACTICA PRA_SOLICITUD_PRACTICA { get; set; }
    }
}
