//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRA_EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRA_EMPRESA()
        {
            this.PRA_CONTACTO = new HashSet<PRA_CONTACTO>();
            this.PRA_EMPLEO = new HashSet<PRA_EMPLEO>();
            this.PRA_PRACTICAS = new HashSet<PRA_PRACTICAS>();
            this.PRA_SOLICITUD_PRACTICA = new HashSet<PRA_SOLICITUD_PRACTICA>();
        }
    
        public long idEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string Cif { get; set; }
        public string Direccion { get; set; }
        public string Mail { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaConvenio { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string FicheroConvenio { get; set; }
        public string Comentarios { get; set; }
        public string Logo { get; set; }
        public int num_contactos { get; set; }
        public int num_practicas { get; set; }
        public int num_empleos { get; set; }
        public int num_solicitudes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRA_CONTACTO> PRA_CONTACTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRA_EMPLEO> PRA_EMPLEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRA_PRACTICAS> PRA_PRACTICAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRA_SOLICITUD_PRACTICA> PRA_SOLICITUD_PRACTICA { get; set; }
    }
}
