//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRA_SOLICITUD_PRACTICA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRA_SOLICITUD_PRACTICA()
        {
            this.PRA_CANDIDATOS = new HashSet<PRA_CANDIDATOS>();
        }
    
        public long idSolicitud { get; set; }
        public long idEmpresa { get; set; }
        public decimal cantidad { get; set; }
        public int num_horas { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public string descripcion_puesto { get; set; }
        public string comentarios { get; set; }
        public Nullable<long> idContacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRA_CANDIDATOS> PRA_CANDIDATOS { get; set; }
        public virtual PRA_EMPRESA PRA_EMPRESA { get; set; }
    }
}
