//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRA_PRACTICAS
    {
        public long idPractica { get; set; }
        public long idEmpresa { get; set; }
        public long idAlumno { get; set; }
        public long idCurso { get; set; }
        public long idTutorEmpresa { get; set; }
        public long idTutorEscuela { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public decimal Duracion { get; set; }
        public int AyudaEstudioMes { get; set; }
        public int HoraSemana { get; set; }
        public string FicheroAnexo { get; set; }
        public string Comentarios { get; set; }
        public string Tipo { get; set; }
        public string PDP_NumFactura { get; set; }
        public string PDP_NumPedido { get; set; }
        public Nullable<decimal> PDP_Precio { get; set; }
        public Nullable<bool> PDP_Matriculado { get; set; }
        public Nullable<bool> PDP_Activado { get; set; }
        public string PDP_Comentarios { get; set; }
        public Nullable<bool> Curriculares { get; set; }
    
        public virtual PRA_EMPRESA PRA_EMPRESA { get; set; }
    }
}
