//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Productos_home = new HashSet<Productos_home>();
            this.Textos_productos = new HashSet<Textos_productos>();
        }
    
        public long id_producto { get; set; }
        public long id_categoria { get; set; }
        public long id_subcategoria { get; set; }
        public string referencia { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<System.DateTime> fecha_ini_validez { get; set; }
        public Nullable<System.DateTime> fecha_fin_validez { get; set; }
        public string recomendado { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<long> ancho { get; set; }
        public Nullable<long> alto { get; set; }
        public Nullable<long> largo { get; set; }
        public int stock { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<long> id_tipo_iva { get; set; }
        public string foto { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos_home> Productos_home { get; set; }
        public virtual Subcategorias Subcategorias { get; set; }
        public virtual Tipos_iva Tipos_iva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Textos_productos> Textos_productos { get; set; }
    }
}
