//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_home
    {
        public long id_producto_home { get; set; }
        public long id_producto { get; set; }
        public string manual { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
