//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOCION
    {
        public int IdPromocion { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdCodigoPromo { get; set; }
    
        public virtual CODIGOS_PROMO CODIGOS_PROMO { get; set; }
    }
}
