//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOCION
    {
        public int IdPromocion { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdCodigoPromo { get; set; }
    
        public virtual CODIGOS_PROMO CODIGOS_PROMO { get; set; }
    }
}
