//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relaciones_restriccion
    {
        public long id_restriccion { get; set; }
        public long id_tipo_relacion_restriccion { get; set; }
        public long id_referenciado { get; set; }
    
        public virtual Restricciones Restricciones { get; set; }
        public virtual Tipos_relacion_restriccion Tipos_relacion_restriccion { get; set; }
    }
}
