//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relaciones_oferta
    {
        public long id_oferta { get; set; }
        public long id_tipo_relacion_oferta { get; set; }
        public long id_referenciado { get; set; }
    
        public virtual Ofertas Ofertas { get; set; }
        public virtual Tipos_relacion_oferta Tipos_relacion_oferta { get; set; }
    }
}
