//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relaciones_oferta
    {
        public long id_oferta { get; set; }
        public long id_tipo_relacion_oferta { get; set; }
        public long id_referenciado { get; set; }
    
        public virtual Ofertas Ofertas { get; set; }
        public virtual Tipos_relacion_oferta Tipos_relacion_oferta { get; set; }
    }
}
