//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relaciones_restriccion
    {
        public long id_restriccion { get; set; }
        public long id_tipo_relacion_restriccion { get; set; }
        public long id_referenciado { get; set; }
    
        public virtual Restricciones Restricciones { get; set; }
        public virtual Tipos_relacion_restriccion Tipos_relacion_restriccion { get; set; }
    }
}
