//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restricciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restricciones()
        {
            this.Relaciones_restriccion = new HashSet<Relaciones_restriccion>();
            this.Textos_restricciones = new HashSet<Textos_restricciones>();
        }
    
        public long id_restriccion { get; set; }
        public long id_tipo_restriccion { get; set; }
        public string codigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relaciones_restriccion> Relaciones_restriccion { get; set; }
        public virtual Tipos_restriccion Tipos_restriccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Textos_restricciones> Textos_restricciones { get; set; }
    }
}
