//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RJL_Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RJL_Personal()
        {
            this.RJL_Registro = new HashSet<RJL_Registro>();
        }
    
        public long id_RJL_Per { get; set; }
        public string Nombre { get; set; }
        public string Foto { get; set; }
        public string Mail { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Dias_Vacaciones { get; set; }
        public Nullable<decimal> Horas_Jornada { get; set; }
        public Nullable<int> Comida_Lunes { get; set; }
        public Nullable<int> Comida_Martes { get; set; }
        public Nullable<int> Comida_Miercoles { get; set; }
        public Nullable<int> Comida_Jueves { get; set; }
        public Nullable<int> Comida_Viernes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RJL_Registro> RJL_Registro { get; set; }
    }
}
