//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RJL_Registro
    {
        public long id_RJL_Registro { get; set; }
        public long id_RJL_Per { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string incidencia { get; set; }
        public string comentarios { get; set; }
    
        public virtual RJL_Personal RJL_Personal { get; set; }
    }
}
