//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbs2_ticker
    {
        public long idTicker { get; set; }
        public string texto { get; set; }
        public string url { get; set; }
        public System.DateTime fecha_inicial { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
    }
}
