//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbs_Nurturing
    {
        public long idNurturing { get; set; }
        public Nullable<long> idCampaña { get; set; }
        public Nullable<int> paso { get; set; }
        public string asunto { get; set; }
        public string cuerpo { get; set; }
        public Nullable<int> NTotal { get; set; }
        public Nullable<int> NClicks { get; set; }
    }
}
