//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbs_inf_landing
    {
        public long idLanding { get; set; }
        public int n_visitas { get; set; }
        public int n_leads { get; set; }
        public int n_leads_unicos { get; set; }
        public int n_nuevos { get; set; }
        public int n_cookies { get; set; }
        public decimal pct_leads { get; set; }
        public decimal pct_leads_unicos { get; set; }
        public decimal pct_leads_nuevos { get; set; }
        public System.DateTime fecha_act { get; set; }
    }
}
