//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbs_Nurturing
    {
        public long idNurturing { get; set; }
        public Nullable<long> idCampaña { get; set; }
        public Nullable<int> paso { get; set; }
        public string asunto { get; set; }
        public string cuerpo { get; set; }
        public Nullable<int> NTotal { get; set; }
        public Nullable<int> NClicks { get; set; }
    }
}
