//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbs_TP_Cursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sbs_TP_Cursos()
        {
            this.sbs_TP_Personas = new HashSet<sbs_TP_Personas>();
        }
    
        public long idTPCurso { get; set; }
        public long idTPContrato { get; set; }
        public long idDocencia { get; set; }
    
        public virtual sbs_TP_Contrato sbs_TP_Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sbs_TP_Personas> sbs_TP_Personas { get; set; }
    }
}
