//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbs_TP_Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sbs_TP_Contrato()
        {
            this.sbs_TP_Cursos = new HashSet<sbs_TP_Cursos>();
        }
    
        public long idTPContrato { get; set; }
        public long idEmpresa { get; set; }
        public long idUserAdmin { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FInicio { get; set; }
        public int NumCursos { get; set; }
        public Nullable<int> NumUsados { get; set; }
        public string Comentarios { get; set; }
        public string url { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual OFF_sbs_Empresa OFF_sbs_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sbs_TP_Cursos> sbs_TP_Cursos { get; set; }
    }
}
