//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbs_inf_landing_n2
    {
        public long idLanding { get; set; }
        public long idOrigen { get; set; }
        public int n_visitas { get; set; }
        public int n_leads { get; set; }
        public int n_leads_unicos { get; set; }
        public int n_nuevos { get; set; }
        public int n_cookies { get; set; }
        public decimal pct_leads { get; set; }
        public decimal pct_leads_unicos { get; set; }
        public decimal pct_leads_nuevos { get; set; }
        public System.DateTime fecha_act { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
    }
}
