//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbs_Task
    {
        public long idTask { get; set; }
        public long idPersonFrom { get; set; }
        public long idPersonTo { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public string comentarios { get; set; }
        public Nullable<System.DateTime> fechaResolucion { get; set; }
    }
}
