//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbs_comunidad_social
    {
        public long id_rrss { get; set; }
        public string titulo { get; set; }
        public string url { get; set; }
        public bool activo { get; set; }
        public int orden { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
