//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbs_TP_Cursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sbs_TP_Cursos()
        {
            this.sbs_TP_Personas = new HashSet<sbs_TP_Personas>();
        }
    
        public long idTPCurso { get; set; }
        public long idTPContrato { get; set; }
        public long idDocencia { get; set; }
    
        public virtual sbs_TP_Contrato sbs_TP_Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sbs_TP_Personas> sbs_TP_Personas { get; set; }
    }
}
