//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbs_comunidad_social
    {
        public long id_rrss { get; set; }
        public string titulo { get; set; }
        public string url { get; set; }
        public bool activo { get; set; }
        public int orden { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
