//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCambiarContrasenas
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public System.DateTime FechaGeneracion { get; set; }
        public Nullable<System.DateTime> FechaUtilizacion { get; set; }
    }
}
