//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCambiarContrasenas
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public System.DateTime FechaGeneracion { get; set; }
        public Nullable<System.DateTime> FechaUtilizacion { get; set; }
    }
}
