//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SORTEO_BECA
    {
        public long idSorteoBeca { get; set; }
        public long idPersona { get; set; }
        public Nullable<bool> chk1 { get; set; }
        public string text_chk1 { get; set; }
        public Nullable<bool> chk2 { get; set; }
        public string text_chk2 { get; set; }
        public Nullable<bool> chk3 { get; set; }
        public string text_chk3 { get; set; }
        public Nullable<bool> chk4 { get; set; }
        public string text_chk4 { get; set; }
        public Nullable<bool> chk5 { get; set; }
        public string text_chk5 { get; set; }
        public Nullable<bool> chk6 { get; set; }
        public string text_chk6 { get; set; }
        public Nullable<bool> chk7 { get; set; }
        public string text_chk7 { get; set; }
        public Nullable<bool> chk8 { get; set; }
        public string text_chk8 { get; set; }
        public Nullable<bool> chk9 { get; set; }
        public string text_chk9 { get; set; }
        public Nullable<bool> chk10 { get; set; }
        public string text_chk10 { get; set; }
        public string ganador_beca { get; set; }
    }
}
