//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SORTEO_BECA_ENCUESTA
    {
        public long idce { get; set; }
        public System.DateTime fecha { get; set; }
        public long idUser { get; set; }
        public Nullable<int> respuesta_1 { get; set; }
        public Nullable<int> respuesta_2 { get; set; }
        public Nullable<int> respuesta_3 { get; set; }
        public Nullable<int> respuesta_4 { get; set; }
        public Nullable<int> respuesta_5 { get; set; }
        public Nullable<int> respuesta_6 { get; set; }
        public Nullable<int> respuesta_7 { get; set; }
        public Nullable<int> respuesta_8 { get; set; }
        public Nullable<int> respuesta_9 { get; set; }
        public Nullable<int> respuesta_10 { get; set; }
        public Nullable<int> respuesta_11 { get; set; }
        public Nullable<int> respuesta_12 { get; set; }
        public Nullable<int> respuesta_13 { get; set; }
        public Nullable<int> respuesta_14 { get; set; }
        public Nullable<int> respuesta_15 { get; set; }
        public Nullable<int> respuesta_16 { get; set; }
        public Nullable<int> respuesta_17 { get; set; }
        public Nullable<int> respuesta_18 { get; set; }
        public Nullable<int> respuesta_19 { get; set; }
        public Nullable<int> respuesta_20 { get; set; }
        public string comentarios { get; set; }
    }
}
