//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SpainBS_Connection : DbContext
    {
        public SpainBS_Connection()
            : base("name=SpainBS_Connection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_EXPERTOS> C_EXPERTOS { get; set; }
        public virtual DbSet<AspNetRoleClaims> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserTokens> AspNetUserTokens { get; set; }
        public virtual DbSet<Atribuciones> Atribuciones { get; set; }
        public virtual DbSet<BEC_SOLICITUD_BECA> BEC_SOLICITUD_BECA { get; set; }
        public virtual DbSet<BLOG_USU> BLOG_USU { get; set; }
        public virtual DbSet<campus_ACCIONES_PERSONA> campus_ACCIONES_PERSONA { get; set; }
        public virtual DbSet<campus_ACL> campus_ACL { get; set; }
        public virtual DbSet<campus_ACTIVACIONES> campus_ACTIVACIONES { get; set; }
        public virtual DbSet<campus_ACTIVACIONES_PDP> campus_ACTIVACIONES_PDP { get; set; }
        public virtual DbSet<campus_AGENDA> campus_AGENDA { get; set; }
        public virtual DbSet<campus_ALERTAS> campus_ALERTAS { get; set; }
        public virtual DbSet<campus_ANUNCIO> campus_ANUNCIO { get; set; }
        public virtual DbSet<campus_ANUNCIO_REL> campus_ANUNCIO_REL { get; set; }
        public virtual DbSet<campus_AREA_FUNCIONAL> campus_AREA_FUNCIONAL { get; set; }
        public virtual DbSet<campus_AUTO_CURSO> campus_AUTO_CURSO { get; set; }
        public virtual DbSet<campus_AUTO_DOCENCIA> campus_AUTO_DOCENCIA { get; set; }
        public virtual DbSet<campus_AUTO_USER> campus_AUTO_USER { get; set; }
        public virtual DbSet<campus_AUTORIA> campus_AUTORIA { get; set; }
        public virtual DbSet<campus_AUX> campus_AUX { get; set; }
        public virtual DbSet<campus_CLASE_ASISTENCIA> campus_CLASE_ASISTENCIA { get; set; }
        public virtual DbSet<campus_CLASE_ENCUESTA> campus_CLASE_ENCUESTA { get; set; }
        public virtual DbSet<campus_CLIENTES_COMERCIAL> campus_CLIENTES_COMERCIAL { get; set; }
        public virtual DbSet<campus_CLIENTES_DOC> campus_CLIENTES_DOC { get; set; }
        public virtual DbSet<campus_CONTENIDO_CURSO> campus_CONTENIDO_CURSO { get; set; }
        public virtual DbSet<campus_CONTENIDO_DOCENCIA> campus_CONTENIDO_DOCENCIA { get; set; }
        public virtual DbSet<campus_CONTENIDO_EXAMEN> campus_CONTENIDO_EXAMEN { get; set; }
        public virtual DbSet<campus_CONTENIDO_PROGRAMA> campus_CONTENIDO_PROGRAMA { get; set; }
        public virtual DbSet<campus_CURSO> campus_CURSO { get; set; }
        public virtual DbSet<campus_CURSO_EXAMEN> campus_CURSO_EXAMEN { get; set; }
        public virtual DbSet<campus_DATA_COMERCIAL> campus_DATA_COMERCIAL { get; set; }
        public virtual DbSet<campus_DOCENCIA> campus_DOCENCIA { get; set; }
        public virtual DbSet<campus_DOCENCIA_ALUMNO_AUTO> campus_DOCENCIA_ALUMNO_AUTO { get; set; }
        public virtual DbSet<campus_DOCENCIA_CONTENIDO_EXAMEN> campus_DOCENCIA_CONTENIDO_EXAMEN { get; set; }
        public virtual DbSet<campus_DOCENCIA_EXAMEN> campus_DOCENCIA_EXAMEN { get; set; }
        public virtual DbSet<campus_DOCENCIA_GRUPO> campus_DOCENCIA_GRUPO { get; set; }
        public virtual DbSet<campus_DOCENCIA_GRUPO_EVALUACION> campus_DOCENCIA_GRUPO_EVALUACION { get; set; }
        public virtual DbSet<campus_DOCENCIA_GRUPO_REC_PRACT> campus_DOCENCIA_GRUPO_REC_PRACT { get; set; }
        public virtual DbSet<campus_DOCENCIA_SUBGRUPO> campus_DOCENCIA_SUBGRUPO { get; set; }
        public virtual DbSet<campus_DOCENCIA_TUTORIAS> campus_DOCENCIA_TUTORIAS { get; set; }
        public virtual DbSet<campus_ED_ANTERIOR> campus_ED_ANTERIOR { get; set; }
        public virtual DbSet<campus_EDUCACION> campus_EDUCACION { get; set; }
        public virtual DbSet<campus_ENCUESTA> campus_ENCUESTA { get; set; }
        public virtual DbSet<campus_EXPERIENCIA_PROFESIONAL> campus_EXPERIENCIA_PROFESIONAL { get; set; }
        public virtual DbSet<campus_FORO> campus_FORO { get; set; }
        public virtual DbSet<campus_FORO_ADJUNTOS> campus_FORO_ADJUNTOS { get; set; }
        public virtual DbSet<campus_FORO_MENSAJE> campus_FORO_MENSAJE { get; set; }
        public virtual DbSet<campus_FORO_RESPUESTA> campus_FORO_RESPUESTA { get; set; }
        public virtual DbSet<campus_IMAGEN> campus_IMAGEN { get; set; }
        public virtual DbSet<campus_INVESTIGA> campus_INVESTIGA { get; set; }
        public virtual DbSet<campus_LH> campus_LH { get; set; }
        public virtual DbSet<campus_LITERALES> campus_LITERALES { get; set; }
        public virtual DbSet<campus_LOG> campus_LOG { get; set; }
        public virtual DbSet<campus_OPINIONES> campus_OPINIONES { get; set; }
        public virtual DbSet<campus_OPINIONES_SOLICITUD> campus_OPINIONES_SOLICITUD { get; set; }
        public virtual DbSet<campus_OTROS> campus_OTROS { get; set; }
        public virtual DbSet<campus_PDP> campus_PDP { get; set; }
        public virtual DbSet<campus_PDP_conex_paquete> campus_PDP_conex_paquete { get; set; }
        public virtual DbSet<campus_PDP_paquete> campus_PDP_paquete { get; set; }
        public virtual DbSet<campus_PLANTILLA_MAIL> campus_PLANTILLA_MAIL { get; set; }
        public virtual DbSet<campus_PUBLICIDAD> campus_PUBLICIDAD { get; set; }
        public virtual DbSet<campus_RD_Asistencia> campus_RD_Asistencia { get; set; }
        public virtual DbSet<campus_RD_Doc> campus_RD_Doc { get; set; }
        public virtual DbSet<campus_RD_DOC_CUR> campus_RD_DOC_CUR { get; set; }
        public virtual DbSet<campus_RD_ListaSeg> campus_RD_ListaSeg { get; set; }
        public virtual DbSet<campus_RD_R> campus_RD_R { get; set; }
        public virtual DbSet<campus_RD_Valoracion> campus_RD_Valoracion { get; set; }
        public virtual DbSet<campus_REC_CP> campus_REC_CP { get; set; }
        public virtual DbSet<campus_REC_CP_TRABAJO> campus_REC_CP_TRABAJO { get; set; }
        public virtual DbSet<campus_RECURSO> campus_RECURSO { get; set; }
        public virtual DbSet<campus_RECURSO_DIRECTO> campus_RECURSO_DIRECTO { get; set; }
        public virtual DbSet<campus_RECURSO_STATUS> campus_RECURSO_STATUS { get; set; }
        public virtual DbSet<campus_REGLAS_ACCIONES> campus_REGLAS_ACCIONES { get; set; }
        public virtual DbSet<campus_REGLAS_AUTOMATIZACION> campus_REGLAS_AUTOMATIZACION { get; set; }
        public virtual DbSet<campus_REGLAS_TIPO_ACCION> campus_REGLAS_TIPO_ACCION { get; set; }
        public virtual DbSet<campus_SEG_COMERCIAL> campus_SEG_COMERCIAL { get; set; }
        public virtual DbSet<campus_SEG_COMERCIAL_INF> campus_SEG_COMERCIAL_INF { get; set; }
        public virtual DbSet<campus_TIPO_ANUNCIO> campus_TIPO_ANUNCIO { get; set; }
        public virtual DbSet<campus_TIPO_AUTOMATIZACION> campus_TIPO_AUTOMATIZACION { get; set; }
        public virtual DbSet<campus_TIPO_CURSO> campus_TIPO_CURSO { get; set; }
        public virtual DbSet<campus_TIPO_RECURSO> campus_TIPO_RECURSO { get; set; }
        public virtual DbSet<campus_TIPO_SOLICITUD_OPINION> campus_TIPO_SOLICITUD_OPINION { get; set; }
        public virtual DbSet<campus_TUTORIA> campus_TUTORIA { get; set; }
        public virtual DbSet<campus_WORKFLOW_AVANCE> campus_WORKFLOW_AVANCE { get; set; }
        public virtual DbSet<campus_WORKFLOW_DOCENCIA> campus_WORKFLOW_DOCENCIA { get; set; }
        public virtual DbSet<campus_WORKFLOW_GRUPO> campus_WORKFLOW_GRUPO { get; set; }
        public virtual DbSet<campus_WORKFLOW_PASO> campus_WORKFLOW_PASO { get; set; }
        public virtual DbSet<campus_WORKFLOW_PREGUNTAS> campus_WORKFLOW_PREGUNTAS { get; set; }
        public virtual DbSet<CampusCursoOnline> CampusCursoOnline { get; set; }
        public virtual DbSet<CampusCursoOnlineAfiliado> CampusCursoOnlineAfiliado { get; set; }
        public virtual DbSet<Carritos> Carritos { get; set; }
        public virtual DbSet<CATEGORIA_CAT> CATEGORIA_CAT { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<CLIENTES_COMENTARIOS> CLIENTES_COMENTARIOS { get; set; }
        public virtual DbSet<Clientes_Intereses> Clientes_Intereses { get; set; }
        public virtual DbSet<CLIENTES_TAG> CLIENTES_TAG { get; set; }
        public virtual DbSet<CodigoPostal> CodigoPostal { get; set; }
        public virtual DbSet<CODIGOS_PROMO> CODIGOS_PROMO { get; set; }
        public virtual DbSet<COMENTARIOS_CMT> COMENTARIOS_CMT { get; set; }
        public virtual DbSet<componer_Curso> componer_Curso { get; set; }
        public virtual DbSet<CVE_CERTIFICADO> CVE_CERTIFICADO { get; set; }
        public virtual DbSet<CVE_PETICION> CVE_PETICION { get; set; }
        public virtual DbSet<CVE_SOLICITUD> CVE_SOLICITUD { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<EDU_Banners> EDU_Banners { get; set; }
        public virtual DbSet<EDU_Productos> EDU_Productos { get; set; }
        public virtual DbSet<EDU_Suscriptores> EDU_Suscriptores { get; set; }
        public virtual DbSet<EMAIL_ACTIVADORES> EMAIL_ACTIVADORES { get; set; }
        public virtual DbSet<EMAIL_CAMPAIGNS> EMAIL_CAMPAIGNS { get; set; }
        public virtual DbSet<EMAIL_CAMPAIGNS_STATUS> EMAIL_CAMPAIGNS_STATUS { get; set; }
        public virtual DbSet<EMAIL_CAMPAIGNS_STATUS_REENVIO> EMAIL_CAMPAIGNS_STATUS_REENVIO { get; set; }
        public virtual DbSet<EMAIL_CLICKS> EMAIL_CLICKS { get; set; }
        public virtual DbSet<EMAIL_CONTENT> EMAIL_CONTENT { get; set; }
        public virtual DbSet<EMAIL_LISTADO_SUSCRIPCIONES> EMAIL_LISTADO_SUSCRIPCIONES { get; set; }
        public virtual DbSet<EMAIL_SERVER> EMAIL_SERVER { get; set; }
        public virtual DbSet<EMAIL_SERVER_ESTADISTICAS> EMAIL_SERVER_ESTADISTICAS { get; set; }
        public virtual DbSet<EMAIL_SERVER_STATUS> EMAIL_SERVER_STATUS { get; set; }
        public virtual DbSet<EMAIL_SUSCRIPCIONES> EMAIL_SUSCRIPCIONES { get; set; }
        public virtual DbSet<enc_ALUMNIO> enc_ALUMNIO { get; set; }
        public virtual DbSet<enc_ENCUESTA> enc_ENCUESTA { get; set; }
        public virtual DbSet<enc_PREGUNTA> enc_PREGUNTA { get; set; }
        public virtual DbSet<enc_TIPO_Pregunta_Valor> enc_TIPO_Pregunta_Valor { get; set; }
        public virtual DbSet<EVENTOS> EVENTOS { get; set; }
        public virtual DbSet<EXPERTOS> EXPERTOS { get; set; }
        public virtual DbSet<EXPERTOS_CARACTERISTICAS> EXPERTOS_CARACTERISTICAS { get; set; }
        public virtual DbSet<FICHERO_FIC> FICHERO_FIC { get; set; }
        public virtual DbSet<FOT_FOTOGRAFIA> FOT_FOTOGRAFIA { get; set; }
        public virtual DbSet<GAL_GALERIA> GAL_GALERIA { get; set; }
        public virtual DbSet<Gastos_envio> Gastos_envio { get; set; }
        public virtual DbSet<GEO_IP> GEO_IP { get; set; }
        public virtual DbSet<Idiomas> Idiomas { get; set; }
        public virtual DbSet<Incidencias> Incidencias { get; set; }
        public virtual DbSet<INF_AUX> INF_AUX { get; set; }
        public virtual DbSet<INF_ENCUESTA> INF_ENCUESTA { get; set; }
        public virtual DbSet<INF_FIN_AREAS> INF_FIN_AREAS { get; set; }
        public virtual DbSet<INF_FIN_CAJA> INF_FIN_CAJA { get; set; }
        public virtual DbSet<INF_FIN_COSTES> INF_FIN_COSTES { get; set; }
        public virtual DbSet<INF_FIN_ESTRUCTURAS_VERSION> INF_FIN_ESTRUCTURAS_VERSION { get; set; }
        public virtual DbSet<INF_FIN_FACTURAS> INF_FIN_FACTURAS { get; set; }
        public virtual DbSet<INF_FIN_SUBAREAS> INF_FIN_SUBAREAS { get; set; }
        public virtual DbSet<INF_FIN_SUBAREAS2> INF_FIN_SUBAREAS2 { get; set; }
        public virtual DbSet<INF_FIN_TAX_TYPES> INF_FIN_TAX_TYPES { get; set; }
        public virtual DbSet<INF_LHO_VENTA> INF_LHO_VENTA { get; set; }
        public virtual DbSet<INF_MK_DATA> INF_MK_DATA { get; set; }
        public virtual DbSet<INF_MK_OBJETIVOS> INF_MK_OBJETIVOS { get; set; }
        public virtual DbSet<Lineas_pedido> Lineas_pedido { get; set; }
        public virtual DbSet<Modos_pago> Modos_pago { get; set; }
        public virtual DbSet<NOTICIAS_NOT> NOTICIAS_NOT { get; set; }
        public virtual DbSet<Ofertas> Ofertas { get; set; }
        public virtual DbSet<OFF_sbs_Contacto> OFF_sbs_Contacto { get; set; }
        public virtual DbSet<OFF_sbs_Empleo> OFF_sbs_Empleo { get; set; }
        public virtual DbSet<OFF_sbs_Empresa> OFF_sbs_Empresa { get; set; }
        public virtual DbSet<OFF_sbs_Practicas> OFF_sbs_Practicas { get; set; }
        public virtual DbSet<OnlineAfiliado> OnlineAfiliado { get; set; }
        public virtual DbSet<OnlineBusqueda> OnlineBusqueda { get; set; }
        public virtual DbSet<OnlineCarrito> OnlineCarrito { get; set; }
        public virtual DbSet<OnlineDeseo> OnlineDeseo { get; set; }
        public virtual DbSet<OnlineOrden> OnlineOrden { get; set; }
        public virtual DbSet<OnlineOrdenProducto> OnlineOrdenProducto { get; set; }
        public virtual DbSet<OnlineOrdenStatus> OnlineOrdenStatus { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<PAR_PARTICIPANTES> PAR_PARTICIPANTES { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<PRA_CANDIDATOS> PRA_CANDIDATOS { get; set; }
        public virtual DbSet<PRA_CONTACTO> PRA_CONTACTO { get; set; }
        public virtual DbSet<PRA_EMPLEO> PRA_EMPLEO { get; set; }
        public virtual DbSet<PRA_EMPRESA> PRA_EMPRESA { get; set; }
        public virtual DbSet<PRA_PRACTICAS> PRA_PRACTICAS { get; set; }
        public virtual DbSet<PRA_SOLICITUD_PRACTICA> PRA_SOLICITUD_PRACTICA { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Productos_home> Productos_home { get; set; }
        public virtual DbSet<PROMOCION> PROMOCION { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Relaciones_oferta> Relaciones_oferta { get; set; }
        public virtual DbSet<Relaciones_restriccion> Relaciones_restriccion { get; set; }
        public virtual DbSet<Restricciones> Restricciones { get; set; }
        public virtual DbSet<RJL_Personal> RJL_Personal { get; set; }
        public virtual DbSet<RJL_Registro> RJL_Registro { get; set; }
        public virtual DbSet<sbs_comunidad_social> sbs_comunidad_social { get; set; }
        public virtual DbSet<sbs_inf_landing> sbs_inf_landing { get; set; }
        public virtual DbSet<sbs_Landing> sbs_Landing { get; set; }
        public virtual DbSet<sbs_Nurturing> sbs_Nurturing { get; set; }
        public virtual DbSet<sbs_Task> sbs_Task { get; set; }
        public virtual DbSet<sbs_TP_Contrato> sbs_TP_Contrato { get; set; }
        public virtual DbSet<sbs_TP_Cursos> sbs_TP_Cursos { get; set; }
        public virtual DbSet<sbs_TP_Personas> sbs_TP_Personas { get; set; }
        public virtual DbSet<sbs2_area_funcional> sbs2_area_funcional { get; set; }
        public virtual DbSet<sbs2_conex_area_tematica> sbs2_conex_area_tematica { get; set; }
        public virtual DbSet<sbs2_conex_curso_area> sbs2_conex_curso_area { get; set; }
        public virtual DbSet<sbs2_conex_curso_tematica> sbs2_conex_curso_tematica { get; set; }
        public virtual DbSet<sbs2_empresas_alumnos> sbs2_empresas_alumnos { get; set; }
        public virtual DbSet<sbs2_faqs> sbs2_faqs { get; set; }
        public virtual DbSet<sbs2_pagos_especiales> sbs2_pagos_especiales { get; set; }
        public virtual DbSet<sbs2_preferencias> sbs2_preferencias { get; set; }
        public virtual DbSet<sbs2_questions> sbs2_questions { get; set; }
        public virtual DbSet<sbs2_tematica> sbs2_tematica { get; set; }
        public virtual DbSet<sbs2_ticker> sbs2_ticker { get; set; }
        public virtual DbSet<Socio> Socio { get; set; }
        public virtual DbSet<SolicitudCambiarContrasenas> SolicitudCambiarContrasenas { get; set; }
        public virtual DbSet<SORTEO_BECA> SORTEO_BECA { get; set; }
        public virtual DbSet<SORTEO_BECA_ENCUESTA> SORTEO_BECA_ENCUESTA { get; set; }
        public virtual DbSet<SUBCATEGORIA_SBC> SUBCATEGORIA_SBC { get; set; }
        public virtual DbSet<Subcategorias> Subcategorias { get; set; }
        public virtual DbSet<SUSCRIPCION_SCR> SUSCRIPCION_SCR { get; set; }
        public virtual DbSet<TAG> TAG { get; set; }
        public virtual DbSet<TAMANO_TAM> TAMANO_TAM { get; set; }
        public virtual DbSet<Test_Categoria> Test_Categoria { get; set; }
        public virtual DbSet<Test_Clientes> Test_Clientes { get; set; }
        public virtual DbSet<Test_Examen> Test_Examen { get; set; }
        public virtual DbSet<Test_Examen_Contenido> Test_Examen_Contenido { get; set; }
        public virtual DbSet<Test_Inventario_Pregunta> Test_Inventario_Pregunta { get; set; }
        public virtual DbSet<Test_Subcategoria> Test_Subcategoria { get; set; }
        public virtual DbSet<Test_Test> Test_Test { get; set; }
        public virtual DbSet<Test_Test_Reglas> Test_Test_Reglas { get; set; }
        public virtual DbSet<Test_Triada_Cerebral> Test_Triada_Cerebral { get; set; }
        public virtual DbSet<Tests_Categorias_Subcategorias> Tests_Categorias_Subcategorias { get; set; }
        public virtual DbSet<Textos_categorias> Textos_categorias { get; set; }
        public virtual DbSet<Textos_modo_pago> Textos_modo_pago { get; set; }
        public virtual DbSet<Textos_productos> Textos_productos { get; set; }
        public virtual DbSet<Textos_restricciones> Textos_restricciones { get; set; }
        public virtual DbSet<Textos_subcategorias> Textos_subcategorias { get; set; }
        public virtual DbSet<Textos_tipo_restriccion> Textos_tipo_restriccion { get; set; }
        public virtual DbSet<Tipos_iva> Tipos_iva { get; set; }
        public virtual DbSet<Tipos_oferta> Tipos_oferta { get; set; }
        public virtual DbSet<Tipos_orden> Tipos_orden { get; set; }
        public virtual DbSet<TIPOS_RELACION> TIPOS_RELACION { get; set; }
        public virtual DbSet<Tipos_relacion_oferta> Tipos_relacion_oferta { get; set; }
        public virtual DbSet<Tipos_relacion_restriccion> Tipos_relacion_restriccion { get; set; }
        public virtual DbSet<Tipos_restriccion> Tipos_restriccion { get; set; }
        public virtual DbSet<TipoSocio> TipoSocio { get; set; }
        public virtual DbSet<TipoVia> TipoVia { get; set; }
        public virtual DbSet<UNI_ALUMNOS> UNI_ALUMNOS { get; set; }
        public virtual DbSet<UNI_PROG_ASIGNATURA> UNI_PROG_ASIGNATURA { get; set; }
        public virtual DbSet<UNI_PROGRAMA> UNI_PROGRAMA { get; set; }
        public virtual DbSet<URL_URL> URL_URL { get; set; }
        public virtual DbSet<VIDEOS_VID> VIDEOS_VID { get; set; }
        public virtual DbSet<campus_CURSO_ASOCIADO> campus_CURSO_ASOCIADO { get; set; }
        public virtual DbSet<campus_PROGRAMA_ASOCIADO> campus_PROGRAMA_ASOCIADO { get; set; }
        public virtual DbSet<elEconomista_Cursos> elEconomista_Cursos { get; set; }
        public virtual DbSet<elEconomista_Noticias> elEconomista_Noticias { get; set; }
        public virtual DbSet<NOTICIAS_RELACION_REL> NOTICIAS_RELACION_REL { get; set; }
        public virtual DbSet<RJL_DiasNoLab> RJL_DiasNoLab { get; set; }
        public virtual DbSet<sbs_inf_landing_n2> sbs_inf_landing_n2 { get; set; }
        public virtual DbSet<sbs2_control_curso> sbs2_control_curso { get; set; }
        public virtual DbSet<sbs2_control_docencia> sbs2_control_docencia { get; set; }
        public virtual DbSet<Tipos_conocimiento_web> Tipos_conocimiento_web { get; set; }
        public virtual DbSet<VW_INF_FIN_ESTRUCTURA_COMPLETA> VW_INF_FIN_ESTRUCTURA_COMPLETA { get; set; }
        public virtual DbSet<ClienteRole> ClienteRoles { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<RolePage> RolePages { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<campus_ASIG_COMERCIAL> campus_ASIG_COMERCIAL { get; set; }
    
        public virtual int ReplaceSQLInjection()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReplaceSQLInjection");
        }
    
        public virtual int sp_Inf_Seg_Comercial(Nullable<long> idComercial, Nullable<int> activo, Nullable<int> futuro)
        {
            var idComercialParameter = idComercial.HasValue ?
                new ObjectParameter("IdComercial", idComercial) :
                new ObjectParameter("IdComercial", typeof(long));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(int));
    
            var futuroParameter = futuro.HasValue ?
                new ObjectParameter("Futuro", futuro) :
                new ObjectParameter("Futuro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inf_Seg_Comercial", idComercialParameter, activoParameter, futuroParameter);
        }
    
        public virtual int sp_update_CampusAccionesPersona(Nullable<long> idPersona, string cookie)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("idPersona", idPersona) :
                new ObjectParameter("idPersona", typeof(long));
    
            var cookieParameter = cookie != null ?
                new ObjectParameter("Cookie", cookie) :
                new ObjectParameter("Cookie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_CampusAccionesPersona", idPersonaParameter, cookieParameter);
        }
    
        public virtual int sp_update_CampusInvestiga(Nullable<long> idPersona, string cookie, Nullable<int> scoring)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(long));
    
            var cookieParameter = cookie != null ?
                new ObjectParameter("Cookie", cookie) :
                new ObjectParameter("Cookie", typeof(string));
    
            var scoringParameter = scoring.HasValue ?
                new ObjectParameter("Scoring", scoring) :
                new ObjectParameter("Scoring", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_CampusInvestiga", idPersonaParameter, cookieParameter, scoringParameter);
        }
    }
}
