//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAMANO_TAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAMANO_TAM()
        {
            this.VIDEOS_VID = new HashSet<VIDEOS_VID>();
        }
    
        public int TAM_ID { get; set; }
        public string TAM_ANCHO { get; set; }
        public string TAM_ALTO { get; set; }
        public string TAM_EXPRESION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIDEOS_VID> VIDEOS_VID { get; set; }
    }
}
