//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Examen_Contenido
    {
        public int Id_Alumno { get; set; }
        public int Id_Test { get; set; }
        public short Num_Intento { get; set; }
        public int Orden { get; set; }
        public int Id_Pregunta { get; set; }
        public short Respuesta { get; set; }
        public Nullable<System.DateTime> FechaHora_Entrega { get; set; }
        public string Huella_Digital { get; set; }
        public Nullable<bool> Ok { get; set; }
    }
}
