//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Test_Reglas
    {
        public int Id_Test { get; set; }
        public short Orden { get; set; }
        public Nullable<long> Id_Curso { get; set; }
        public Nullable<int> Id_Categoria { get; set; }
        public Nullable<int> Id_Subcategoria { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public System.DateTime Fecha_Ult_Modificacion { get; set; }
    }
}
