//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Test
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Normas { get; set; }
        public string Comentarios_Iniciales { get; set; }
        public string Comentarios_Finales { get; set; }
        public string Comentarios_Internos { get; set; }
        public int Tiempo { get; set; }
        public int Num_Preguntas { get; set; }
        public int Acierto_Suma { get; set; }
        public decimal Error_Resta { get; set; }
        public int Apto_Puntos { get; set; }
        public short Nivel_Dificultad { get; set; }
        public Nullable<long> Id_Curso { get; set; }
        public short Num_Intentos { get; set; }
        public bool Hacerlo_En_Partes { get; set; }
        public bool Baja { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public System.DateTime Fecha_Ult_Modificacion { get; set; }
        public int Info_Num_Participantes { get; set; }
        public int Info_Num_Terminados { get; set; }
        public int Info_Num_Aptos { get; set; }
        public short Info_Nivel_Dificultad_Medio { get; set; }
        public decimal Info_Puntuacion_Media { get; set; }
        public bool Interpretado { get; set; }
        public Nullable<long> idClienteTest { get; set; }
        public bool Abierto { get; set; }
        public string Descripcion_Publica { get; set; }
        public string Meta_Title { get; set; }
        public string Meta_Description { get; set; }
        public string Meta_Keywords { get; set; }
        public string Meta_Url { get; set; }
        public string Meta_Author { get; set; }
    }
}
