//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Examen
    {
        public long Id_Alumno { get; set; }
        public int Id_Test { get; set; }
        public short Num_Intento { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<long> Id_Docencia { get; set; }
        public Nullable<long> Id_Curso { get; set; }
        public Nullable<System.DateTime> FechaHora_Inicio { get; set; }
        public Nullable<System.DateTime> FechaHora_Fin { get; set; }
        public Nullable<int> Puntuacion { get; set; }
        public decimal Nivel_Dificultad { get; set; }
        public Nullable<int> Minutos { get; set; }
        public Nullable<bool> Apto { get; set; }
        public string Huella_Digital { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> Nota_Normalizada { get; set; }
        public Nullable<long> idMail { get; set; }
    }
}
