//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Inventario_Pregunta
    {
        public int id { get; set; }
        public string Pregunta_Texto { get; set; }
        public string Pregunta_Adjunto { get; set; }
        public string Pregunta_Url { get; set; }
        public string Interpretacion { get; set; }
        public string Respuesta_1 { get; set; }
        public string Respuesta_2 { get; set; }
        public string Respuesta_3 { get; set; }
        public string Respuesta_4 { get; set; }
        public string Respuesta_5 { get; set; }
        public string Respuesta_6 { get; set; }
        public string Respuesta_7 { get; set; }
        public string Respuesta_8 { get; set; }
        public string Respuesta_9 { get; set; }
        public string Respuesta_10 { get; set; }
        public short Respuesta_Correcta { get; set; }
        public short Nivel_Dificultad { get; set; }
        public Nullable<long> id_Curso { get; set; }
        public int id_Categoria { get; set; }
        public Nullable<int> id_Subcategoria { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public System.DateTime Fecha_Ult_Modificacion { get; set; }
        public bool Baja { get; set; }
        public int Info_Num_Participantes { get; set; }
        public int Info_Num_Aciertos { get; set; }
    }
}
