//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Clientes
    {
        public long idClienteTest { get; set; }
        public string nombre { get; set; }
        public string logo { get; set; }
        public string dominio { get; set; }
        public string plantilla_test_digital { get; set; }
    }
}
