//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Clientes
    {
        public long idClienteTest { get; set; }
        public string nombre { get; set; }
        public string logo { get; set; }
        public string dominio { get; set; }
        public string plantilla_test_digital { get; set; }
    }
}
