//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Textos_subcategorias
    {
        public long id_subcategoria { get; set; }
        public long id_idioma { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual Idiomas Idiomas { get; set; }
        public virtual Subcategorias Subcategorias { get; set; }
    }
}
