//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Textos_categorias
    {
        public long id_categoria { get; set; }
        public long id_idioma { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Idiomas Idiomas { get; set; }
    }
}
