//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoVia
    {
        public long idTipoVia { get; set; }
        public string Nombre { get; set; }
        public string Alias1 { get; set; }
        public string Alias2 { get; set; }
        public string Alias3 { get; set; }
        public string Alias4 { get; set; }
        public string Alias5 { get; set; }
        public string Alias6 { get; set; }
        public string Alias7 { get; set; }
    }
}
