//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNI_PROG_ASIGNATURA
    {
        public long id_upa { get; set; }
        public long id_up { get; set; }
        public string nombre { get; set; }
        public Nullable<long> id_programa_sbs { get; set; }
        public long id_curso_sbs { get; set; }
        public string comentarios { get; set; }
    
        public virtual UNI_PROGRAMA UNI_PROGRAMA { get; set; }
    }
}
