//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNI_PROGRAMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNI_PROGRAMA()
        {
            this.UNI_ALUMNOS = new HashSet<UNI_ALUMNOS>();
            this.UNI_PROG_ASIGNATURA = new HashSet<UNI_PROG_ASIGNATURA>();
        }
    
        public long id_up { get; set; }
        public string universidad { get; set; }
        public string curso { get; set; }
        public string nombre_programa { get; set; }
        public long id_programa_sbs { get; set; }
        public string comentarios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNI_ALUMNOS> UNI_ALUMNOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNI_PROG_ASIGNATURA> UNI_PROG_ASIGNATURA { get; set; }
    }
}
