//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL_URL
    {
        public int URL_ID { get; set; }
        public string URL_NOMBRE { get; set; }
        public string URL_DIRECCION { get; set; }
        public Nullable<int> URL_IDNOT { get; set; }
    
        public virtual NOTICIAS_NOT NOTICIAS_NOT { get; set; }
    }
}
