//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEOS_VID
    {
        public int VID_ID { get; set; }
        public Nullable<int> VID_NOTID { get; set; }
        public Nullable<int> VID_TAMID { get; set; }
        public string VID_DIRECCION { get; set; }
    
        public virtual NOTICIAS_NOT NOTICIAS_NOT { get; set; }
        public virtual TAMANO_TAM TAMANO_TAM { get; set; }
    }
}
