//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEOS_VID
    {
        public int VID_ID { get; set; }
        public Nullable<int> VID_NOTID { get; set; }
        public Nullable<int> VID_TAMID { get; set; }
        public string VID_DIRECCION { get; set; }
    
        public virtual NOTICIAS_NOT NOTICIAS_NOT { get; set; }
        public virtual TAMANO_TAM TAMANO_TAM { get; set; }
    }
}
