//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campus_sbs_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_INF_FIN_ESTRUCTURA_COMPLETA
    {
        public int VersionID { get; set; }
        public string VersionNombre { get; set; }
        public Nullable<bool> VersionActiva { get; set; }
        public int AreaID { get; set; }
        public string AreaNombre { get; set; }
        public string TipoCategoria { get; set; }
        public int AreaOrden { get; set; }
        public Nullable<int> SubareaID { get; set; }
        public string SubareaNombre { get; set; }
        public Nullable<bool> TieneHijos { get; set; }
        public Nullable<int> SubareaOrden { get; set; }
        public Nullable<int> Subarea2ID { get; set; }
        public string Subarea2Nombre { get; set; }
        public Nullable<int> Subarea2Orden { get; set; }
    }
}
